elonafoobar/elonafoobar

message.cpp
Close #10.
The definition of `_s` differs from the declaration of that.
=> Fix invalid signature

snail/font.hpp, std.cpp
Close #13.
The font file is searched in `font/` directory.
=> Use font1 and font2 in config.json instead of hard-coded filename

std.cpp
Close #22.
SDL library clips the source rectangle before copying the source texture.
Black: out of range
White: texture copied from or to
Red: copied or drawn region
=> Fix glitch in screen edge

cell_draw.cpp, std.cpp
Close #24.
The current behavior is not complete, but improved.
Since this commit, you have to prepare `graphic/interface_ex.png`, `graphic/interface_ex2.png` and `graphic/interface_ex3.png` to play Elona Foobar. They can be generated from `graphic/interface.bmp`(You can find it in your original or variants Elona folder).
1. Create 3 files from part of `graphic/interface.bmp`.
* `graphic/interface_ex.png`: x=0, y=656, width=144, height=144
* `graphic/interface_ex2.png`: x=144, y=704, width=48, height=48
* `graphic/interface_ex3.png`: x=144, y=752, width=864, height=48
2. Apply this filter:
* Alpha: `255 - average of RGB`
* R: `255 - R`
* G: `255 - G`
* B: `255 - B`
The license of `graphic/interface.bmp` is not clear so these three files are not included in Elona Foobar repository.
=> Fix glitch of shadow

Makefile, snail/Makefile
Close #31.
Create automatically "runtime", "bin", "snail/bin", and "snail/bin/detail".
=> Add `mkdir` to Makefile

elona.hpp, init.cpp, main.cpp
Close #46.
To avoid SDL's hack.
=> Rename elona::main() to elona::run()

draw.cpp, elona.hpp, elonacore.cpp, init.cpp, message.cpp, set_option.cpp, std.cpp
It is very confusing that the order of parameters of `gzoom` is different that of `gcopy`.
destination width
destination height
window id
source x
source y
source width
source height
mode (unused)
window id
source x
source y
source width
source height
destination width
destination height
=> Change the order of gzoom()'s parameters

elonacore.cpp
Close #76.
Since this commit, the deadlines of all quests are one day at least.
=> Fix too short deadline

calc.cpp, calc.hpp, proc_event.cpp
Close #84.
This commit corrects PR #61.
Restore the definition of `calcobjlv()` and fix the first argument of `flt()` when generating quest rewards.
=> Fix calcobjlv()

snail/detail/sdl.cpp
Close #99.
A nested namespace declaration had remained at #100. This commit fixes it.
=> Downgrade C++ version to 14

init.cpp
Close #116.
`break` is used where to need `continue`.
=> Fix Foobar quiting when rolling attributes

elonacore.cpp
Close #127.
Now background is rendered at casino.
=> Fix glitch at casino

std.cpp
Close #137.
Replace tab character with 4 spaces before drawing text.
=> Draw tab character properly

README.md, config.cpp, draw.cpp, draw.hpp, elonacore.cpp, position.hpp, set_option.cpp, variables.hpp
Close #89.
Add one new option "hpBar" in `config.json`. The meaning of value is compatible with omake, i.e.,
0: Don't show
1: Show left side
2: Show right side
=> Show pets' HP bar like omake

debug.cpp, elonacore.cpp
Close #161.
You can manually enter voldemort mode by hitting F12.
=> Disable voldemort mode by default

calc.cpp, cat.hpp, elona.hpp, putit.hpp
Close #163.
Some compilers do not define `nullptr_t` in global namespace, so replace them with `std::nullptr_t`.
=> Add std namespace to nullptr_t

elonacore.cpp
Close #196.
Do not use global state, instead refer to local variable.
=> Fix not being able to delete save data

std.cpp
Closes #225
Fixed a problem that the background of the prompt text becomes black.
Probably the cause is that blend_mode is always none.
So I fixed that blend_mode will be blend when color isn't {0,0,0,0}
|▼Before|▼After|
|:--:|:--:|
|![2018-05-02 03 05 17](https://user-images.githubusercontent.com/16176282/39486015-b13f861e-4db5-11e8-9ee2-e713d3ce3458.png)|![2018-05-02 03 02 21](https://user-images.githubusercontent.com/16176282/39485901-45b6097c-4db5-11e8-8eb0-c368ff7d9e51.png)|
=> Fix selected text at the prompt filled black

CMakeLists.txt
Close #228.
* Add `add_definitions(-D_UNICODE)` to `CMakeLists.txt`.
* Move declaration about snail lib to reflect added definitions in compiling snail lib.
=> Add _UNICODE flag for Visual Studio

elonacore.cpp
Close #227.
Replace some `elona::filesystem::path()` with `boost::filesystem::path()`.
=> Delete unnecessary executable directory

config.cpp, config.hpp, elonacore.cpp, set_option.cpp
Close #246.
- New option: "autosave"
- 0: disable autosave(default), 1: enable autosave
- You can save game via [F2] as before regardless of whether autosave is disabled or not.
=> Disable autosave

elonacore.cpp, magic.cpp
Close #247.
- Crash when wizard's dream happens during sleeping.
- Crash when reading uncursed/blessed scrolls of wonder.
- Crash when hearing favorite skills of adventurers.
- Crash when trying to train skills from adventurers.
- Crash when eating the corpse of <Little sister>.
- Crash when speaking to trainer.
- Crash when reading scrolls of growth.
- Crash when reading scrolls of gain attribute.
The cause of the above issues is the same as each other. It is missing empty check of `boost::optional<ability_data>`, which is result of `ability_db::operator[]`.
=> Add empty check of the_ability_db

config.cpp
Close #254.
New default value is large C, compatible with vanilla.
=> Fix default value of key_close

cat.cpp, lang/en/buff.lua, runtime/config.json
English option fails at startup because of a typo in `buff.lua`. Also, the name of the English font is wrong. This patch fixes both. It also adds a descriptive error message if loading a Lua script fails.
=> Fix English language option

elonacore.cpp, variables.hpp
Close #267.
Pass a proper performer who actually performs to `skillexp()`.
=> Fix strange performance skill

config.cpp, util.hpp
Close #261.
Skip BOM in these files:
- config.json
- autopick
- art.log
- ndata.csv
- ndata-e.csv
- name.csv
- lastwords.txt
- lastwords-e.txt
- qname.s1
- gdatan.s1
- mdatan.s1
- cdatan.s1
- cdatan2.s1
- cdatan3.s1
- custom talk files
=> Skip BOM at the beginning of text files

draw.cpp, draw.hpp, initialize_map.cpp
Close #268.
- Shorten duration until damage popup disappears (50 -> 20 frames).
- Clear damage popups when entering another map.
- Damage popups were remained even if you exit current map and enter another map before.
- Limit the max number of damage popups (20: oomEx compatible).
- The digit(20) should be configurable.
- About 200 damage popups were shown at once before.
- Increment damage popups' frame even if out of view.
- Old damage popups were left if they were out of view before.
=> Fix performance hit by many damage popup

CMakeLists.txt, cell_draw.cpp, ctrl_file.cpp, elonacore.cpp, event.cpp, event.hpp, init.cpp, initialize_map.cpp, magic.cpp, map_cell.cpp, map_cell.hpp, mef.cpp, mef.hpp, proc_event.cpp, talk_npc.cpp, talk_unique.cpp, variables.hpp, wish.cpp
#284
Moves map effect/cell/event methods to `mef.cpp`/`map_cell.cpp`/`event.cpp`.
=> Refactor: Move methods to mef.cpp/map_cell.cpp/event.cpp

item.cpp, item.hpp
Close #311.
- Fix infinite loop in `inv_compress()`.
- Fix crashes when `inv_compress()` is called.
- `inv_getfreeid()` returned an invalid index when `inv_compress()` is called.
=> Fix infinite loop in inv_compress()

deps/install.bat
Close #313.
- Suppress mkdir's warning when directory already exists.
- Use SDL2_image's `zlib1.dll`, instead of SDL2_TTF's.
=> Fix DLL loading error

menu.cpp
Close #283.
Calling `noteinfo()` without `noteset()` causes bad alloc error. Deleted it.
=> Fix bad allocation when opening journal

std.cpp
Close #326.
Delete unnecessary reallocation of buffer. Even if the buffer size is enough to accept a new line, we resized buffer and inserted extra new lines before. As a result, there were too many extra blank lines in journal menu.
=> Fix too many blank lines in journal

input.cpp
Close #322.
Add missing condition and handle `key_cancel` correctly. I split 1 function into 2 functions, `input_text_dialog()` and `input_number_dialog()`, and at that time I deleted these lines, I guess.
=> Fix being unable to cancel number prompt

animation.cpp, draw.cpp
Close #328.
This implementation is not complete, but it will take a bit long time to replace all `gfdec`/`gfdec2()`.
=> Replace gfdec/gfdec2() with set_color_mod()

building.cpp, character_status.cpp, command.cpp, elona.hpp, elonacore.cpp, initialize_map.cpp, magic.cpp, main_menu.cpp, mapgen.cpp, message.cpp, text.cpp
Close #333.
`await()` post pending input events to `input` class, and this class increments key repeating count when receiving key pressing events. During seeing quest board, `await()` is called very frequently so key repeating count are also incremented frequently. In Foobar some of keys are not regarded as pressed if their repeating count are not equal to 0. Thus, ESC key does not work in front of quest board.
Delete unnecessary `await()`, especially called without argument(default value: 0).
=> Delete unnecessary await()

elonacore.cpp
Close #342.
The cause is that `countdig` was initialized every time.
=> Fix being unable to dig wall

config.cpp, config.hpp, set_option.cpp, shop.cpp
Close #343.
Add new option "restock_interval". It represents interval until a shopkeeper restock his/her goods. (0-10 days)
If you set to 0, shopkeeper's inventory is updated every time you talk to him/her.
=> Add new option "restock_interval"

ctrl_file.cpp, putit.hpp
Close #350.
Do not compress save data by gzip. Only map data(`*.{map,idx,obj}`) is gzip-compressed.
Important note:
**With this change, v0.2.3's save data is not compatible v0.2.4's.**
=> Do not compress save data

.travis.yml, CMakeLists.txt, Makefile, Makefile.win, appveyor.yml, bench/ai.cpp, bench/magic.cpp, bench/util.cpp, bench/util.hpp, message.cpp, snail/hsp/headless.cpp, snail/input.cpp, thirdparty/hayai/CMakeLists.txt, thirdparty/hayai/hayai.hpp, thirdparty/hayai/hayai_benchmarker.hpp, thirdparty/hayai/hayai_clock.hpp, thirdparty/hayai/hayai_compatibility.hpp, thirdparty/hayai/hayai_console.hpp, thirdparty/hayai/hayai_console_outputter.hpp, thirdparty/hayai/hayai_default_test_factory.hpp, thirdparty/hayai/hayai_fixture.hpp, thirdparty/hayai/hayai_json_outputter.hpp, thirdparty/hayai/hayai_junit_xml_outputter.hpp, thirdparty/hayai/hayai_main.hpp, thirdparty/hayai/hayai_outputter.hpp, thirdparty/hayai/hayai_posix_main.cpp, thirdparty/hayai/hayai_test.hpp, thirdparty/hayai/hayai_test_descriptor.hpp, thirdparty/hayai/hayai_test_factory.hpp, thirdparty/hayai/hayai_test_result.hpp
Adds some benchmarking to determine the performance impact of future code changes. This will be used to determine the impact of things like running many user-generated callbacks at various parts of the code. Since the main tenant of ElonaFoobar will become extensibility without the need to fork the entire game for non-trivial features, it's important that the extensibility doesn't come at the cost of performance. We could provide benchmark differences for major features inside pull requests.
Running `make bench` will create the benchmark executable in place of the game executable.
- Added `hayai` benchmarking framework.
- Added some benchmarks for allies fighting, many fast monsters wandering, chained explosions, and Ragnarok.
=> Add benchmark feature

appveyor.yml
AppVeyor failed due to time out at the same line(`7z x elona122.zip > nul`).
To detect the cause, delete `> nul`.
=> Fix AppVeyor failure

appveyor.yml
Finally, I found out the actual cause of #449. This is AppVeyor's log:
```
appveyor DownloadFile http://ylvania.style.coocan.jp/file/elona122.zip
Downloading elona122.zip (28,778,083 bytes)...100%
7z x elona122.zip
7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04
Scanning the drive for archives:
1 file, 28778083 bytes (28 MiB)
Extracting archive: elona122.zip
--
Path = elona122.zip
Type = zip
Physical Size = 28778083
Would you like to replace the existing file:
Path:     .\elona\data\board.txt
Size:     14687 bytes (15 KiB)
Modified: 2010-05-08 14:32:28
with the file from archive:
Path:     elona\data\board.txt
Size:     14687 bytes (15 KiB)
Modified: 2010-05-08 14:32:28
? (Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? 
```
Add `-y` option(answer yes …
=> Add -y option(answer yes to all prompt) to 7z in appveyor.yml

casino.cpp
Close #456.
The wrong value to indicate the casino routine had finished was being returned.
=> Fix not being able to quit in the casino

casino.cpp
Closes #457.
Changes the formula for the potion of cure corruption reward from blackjack to use omake's formula. The chance is `(wins + 1)` out of 10, so 4 wins makes a 50% chance.
=> Use omake's formula for casino cure corruption potion reward

CMakeLists.txt, elonacore.cpp, tests/elonacore.cpp
Close #454.
- Reworks `cutname` to recognize UTF-8 multibyte sequences. In strings with multibyte sequences, each multibyte sequence counts as length 2.
- Added a test for `cutname`.
=> Rework name splitting algorithm

draw.cpp, draw.hpp, init.cpp
Closes #443.
Allocates memory for damage popups at game start and reinitializes them when they become invalid.
=> Preallocate memory for damage popups

elonacore.cpp
Close #450.
They now drop rods of wishing as it seems to Noa intended.
=> Fix loot of loads of Chaos Castles

get_random_npc_id.cpp
Close #446.
Now, they appear only once except for scroll of ally.
=> Check generation count of certain unique monsters

character.cpp
Close #471.
`chara_find()` returns 0 if not found, and the result is passed to `chara_vanquish()`. Then, PC is killed by the function.
Now, `chara_vanquish()` does not kill PC.
=> Fix PC dying in main scenario

config.cpp, message.cpp, snail/hsp/sdl.cpp, snail/input.cpp, std.cpp
Closes #442. Closes #275.
Allows the numpad enter key to be used wherever enter can be used, and allows shift to be used with the numpad movement keys.
=> Improve handling of numpad with shift/allow usage of numpad enter

card.cpp
Close #476.
It is work-around. We should refactor the structure of `struct item` and rewrite this code.
1. Store the deck to variable `tmp`.
1. Delete the deck by assigning 0 to `item#number`.
1. Invoke `itemcreate()` to create a card. Your inventory has at least 1 empty slot because the deck was deleted just now.
1. Show information about the card.
1. Delete the card by assigning 0 to `item#number`.
1. Restore the deck from `tmp`.
=> Fix crash in using deck

elonacore.cpp
Close #451.
Move `fishstat` to static storage.
=> Fix fishing failing more often than vanilla

food.cpp
Close #459.
Weight will not be over the upper limit.
Weight will be over the upper limit if the character's satiety is Bloated.
Weight will be over the upper limit at random if the satiety is very high. This threshold("very high") can be over only by eating stomafillia.
=> Adjust PC's weight

ui.cpp, ui.hpp
Close #295.
Hides the stair positions in the minimap, unless Voldemort is enabled. When playing legitimately, it could give an unexpected advantage.
=> Hide stair positions in minimap unless using Voldemort

input.cpp, input.hpp
Close #452.
Adds a flag (default `true`) that limits the length of text in the input box. If `false`, it still prevents too large textures by cutting off the presented text and adding ellipses, but it will still return the fully typed in text. If the input length becomes a problem (like for wishing) it can be set to `false`.
=> Add length limiting option to message box input

CMakeLists.txt, appveyor.yml, cmake/copy_nonexisting.cmake
Close #436.
Introduces a function to replace `copy_if_different` since it lacks directory support. Now the config file and others shouldn't be overwritten on rebuild.
=> Don't copy files over if they exist on build

snail/input.cpp
Close #242.
Turns off the IME if a keyboard input event is received instead of a text editing/text input event.
=> Fix enter key not working sometimes

character.cpp
Sets the `index` member of characters that are relocated. Before it wasn't getting set after relocation, and strange things were happening.
=> Set the relocated character's index value

item.cpp
Like #516, item's index is sometimes overwritten by different one.
- `item_copy()`
- `item_exchange()`
- `item_delte()`
=> Fix contradiction of item index

README.md
Close #538.
Adds note that files that already exist should not be overwritten by vanilla 1.22 files.
=> Add note to avoid overwriting files in README

ability.cpp, random.hpp
Close #536.
- Fix formula to avoid overflow.
- Delete `assert` in `rnd()`.
- Limit range of `rnd()`. If passing 0 or smaller to `rnd`, it just returns 0.
=> Fix exp overflow

elonacore.cpp, init.cpp, input.cpp, main_menu.cpp, snail/input.cpp, snail/input.hpp
Close #535.
Implements the `autoNumlock` option for Windows and allows the Clear key (which is numpad key 5) to be used for passing turns. This does not fix the behavior of pressing Shift and using the numpad with NumLock on, as it appears to be a Windows-specific issue. It seems `autoNumlock` was a workaround to avoid the issues caused by turning NumLock on and trying to use it, so this might suffice.
The issue still outstanding is forcing Windows to keep Shift pressed when pressing a numpad key with shift pressed and NumLock on. I'm not sure this is feasible.
=> Implement autonumlock/Add "Clear" as wait key

main_menu.cpp, std.cpp, ui.cpp, ui.hpp
Close #93.
Removes the limit of savefiles and allows pagination. Also fixes a small visual glitch caused by reading in too many bytes from the savefile header.
=> Add save screen pagination beyond 5 savefiles

message.cpp
Close #543.
Moves the message box print position up by a single pixel to avoid rendering errors.
=> Move message print position up by one

item.cpp
Close #574.
Check "mode" before refreshing cells in `item_remove()`.
=> Fix removal of item info

ctrl_file.cpp, elonacore.cpp, gdata.cpp, gdata.hpp, init.cpp, testing.cpp, tests/serialization.cpp, turn_sequence.cpp, ui.cpp
Close #580.
Currently, `foobar_save.s1` does not have foobar's version so...
1. delete old meta data file, `foobar_save.s1`,
2. set v0.2.5 to `foobar_data`.
Now, you can detect that the version is v0.2.5 and write migration code in `migrate_save_data()`.
Then, when saving in v0.2.6 or later, write meta data into `foobar_data.s1`. Its filename differs from old one so we can know if the save data is created in v0.2.5 or not.
=> Save foobar version and add migration code

character_making.cpp
- Allow pressing escape to cancel at the final prompt (was accidentally changed)
- Only restore the alias if it's been chosen (i.e. not after pressing F1)
=> Fix minor charamake issues

character_making.cpp, filesystem.cpp, filesystem.hpp, init.cpp
Close #550.
- Change naming convention of save folder from `sav_XXX` to random name(generated by `boost::filesystem::unique_path()`).
- Due to the first change, validation of character's name comes to be unnecessary. Now, there are no limit of your character name!
=> Change naming convention of save

ctrl_file.cpp, elonacore.cpp, map.cpp, map.hpp, variables.hpp
Close #593.
How to update broken map data in v0.2.5.
If the map is regenerated every time like town map,
1. Delete duplicated items.
2. Place items on the ground.
Otherwise,
1. Update `map` based on `inv`.
=> Fix broken map

doc/api/classes/LuaCharacter.luadoc, lua_env/lua_api.cpp
Adds `LuaCharacter.experience`.
Mainly needed for reproducing #595.
=> API: Add LuaCharacter.experience

src/cat.cpp, src/filesystem.cpp, src/filesystem.hpp, src/snail/font.cpp, src/snail/hsp.hpp, src/snail/hsp/headless.cpp, src/snail/hsp/sdl.cpp, src/std.cpp
Fix handling of font's filepath which contains non-ASCII characters.
On Windows, when constructor of `boost::filesystem::path` receives `char*` or `std::string`, it regard the passed string as ANSI filepath, not UTF8 filepath although we always encode string in UTF8. To avoid this problem, we prepare `elona::filesystem::u8path`, which is similar to `std::filesystem::u8path` provided in C++17 or later, but the function is not used in this case.
=> Fix filepath handling

src/i18n.cpp, src/tests/i18n.cpp, src/tests/i18n_builtins.cpp, src/thirdparty/microhil/hil.hpp
Adds `itemname` and `itembasename` as interpolation functions in translations. They are needed by many of the changes for externalizing text.
=> Add itemname/itembasename as I18N functions

src/i18n.cpp, src/tests/i18n_builtins.cpp
Consolidate `he2`, `his2` and `him2` into single functions for I18N.
=> I18n: Rename he2, his2, him2 to he, his, him

src/elonacore.cpp, src/enums.hpp, src/input.cpp, src/input.hpp, src/menu.cpp, src/turn_sequence.cpp
- Adjusts the numpad wait and enter keys to be delayed.
- Adjusts shortcut keys to ~~never repeat~~ properly repeat.
- Increases delay on wait keypress.
=> Adjust keywait for numpad wait/enter and shortcut key

src/ctrl_file.cpp, src/elona.hpp, src/elonacore.cpp, src/init.cpp, src/input.cpp, src/item.cpp, src/network.cpp, src/std.cpp, src/tcg.cpp, src/testing.cpp, src/text.cpp, src/variables.hpp
Delete unused functions and their prototype declarations mainly in `src/elona.hpp`. Most of them are HSP built-in or imported DLL functions.
=> Delete unused prototype declarations

src/input.cpp
Closes #625.
Delays the enter key if `key_enter` is already set in `key_check()` beforehand. Otherwise, those presses of the enter key won't be delayed.
```lua
Event.register(Event.EventKind.ScriptLoaded, function() Item.create(Chara.player().position, 313, 1) end)
```
=> Delay enter if key_enter is already detected as key pressed

src/character.hpp, src/dmgheal.cpp, src/dmgheal.hpp, src/main.hpp, src/variables.hpp
Close #633.
- Corrects a wrong translation string key.
- Refactors `dmghp()` so the arguments are more readable and optional parameter existence is clearer.
- Adds implicit conversion operator to `character` that decays to `int`, so it can be passed as arguments to functions taking an `int` index.
=> Fix death cause message/refactor dmghp()

.luacheckrc, doc/api/input.luadoc, src/lua_env/lua_api.cpp, src/tests/lua/input.lua, src/tests/lua_api.cpp
Add an `Input` API for prompting the player.
```lua
local Input = Elona.require("Input")
local GUI = Elona.require("GUI")
local Enums = Elona.require("Enums")
local table = Elona.require("table")
local function make_sandbag(x, y, chara_id)
Item.create(x, y, 733, 1)
local chara = Chara.create(x, y, chara_id)
chara:set_flag(Enums.CharaFlag.IsHungOnSandBag, true)
return chara
end
local function choice()
GUI.txt("Which? ")
local choices = {"First", "Second", "Third"}
local result = Input.prompt_choice(table.unpack(choices))
if result then
GUI.txt("You chose \"" .. choices[result] .. "\". ")
else
GUI.txt("Never mind. ")
end
end
local function text()
local result = …
```
=> Add Input API

src/animation.cpp, src/blending.cpp, src/building.cpp, src/casino.cpp, src/casino_card.cpp, src/cell_draw.cpp, src/character_making.cpp, src/crafting.cpp, src/ctrl_inventory.cpp, src/draw.cpp, src/elona.hpp, src/elonacore.cpp, src/input.cpp, src/magic.cpp, src/main_menu.cpp, src/menu.cpp, src/message.cpp, src/network.cpp, src/proc_event.cpp, src/set_option.cpp, src/snail/hsp.hpp, src/snail/hsp/headless.cpp, src/snail/hsp/sdl.cpp, src/std.cpp, src/talk.cpp, src/tcg.cpp, src/ui.cpp
#603 
Reduces global states and explicit parameters.
- Add `gcopy_c()`, a variation of `gcopy()`.
- Organize `grotate()`'s signature.
- Delete width/height from `gmode()`'s parameters.
=> Refactor gmode()

runtime/locale/en/common.hcl, runtime/locale/en/magic.hcl, runtime/locale/jp/common.hcl, runtime/locale/jp/magic.hcl, src/i18n.cpp, src/i18n.hpp, src/magic.cpp, src/thirdparty/microhcl/hcl.hpp
Migrates magic-related strings to the new format.
```lua
local Enums = Elona.require("Enums")
local GUI = Elona.require("GUI")
local Iter = Elona.require("Iter")
local Map = Elona.require("Map")
local table = Elona.require("table")
local potions = {736, 711, 706, 626, 577, 566, 559, 519, 433, 432,
429, 382, 379, 376, 375, 372, 370, 368, 364, 287, 286, 285, 262, 76,
75, 74, 72, 71, 70, 69, 68, 30, 29, 28, 27}
local scrolls = {737, 709, 638, 632, 549, 515, 509, 508, 507, 506,
502, 501, 500, 479, 431, 430, 411, 398, 395, 390, 389, 388, 384, 363,
362, 288, 245, 244, 243, 242, 236, 209, 17, 16, 15, 14}
local rods = {581, 570, 565, 551, 545, 518, 517, 485, 480, 412, 391,
385, 377, 366, …
```
=> I18N: Externalize magic-related strings

src/lua_env/lua_env.cpp
Otherwise an exception will be thrown because global variables are
disallowed currently.
=> Prepend functions in inline lua with "local"

README-jp.md, README.md, runtime/locale/en/config.hcl, runtime/locale/jp/config.hcl, runtime/mods/core/config/config_def.hcl, src/config.cpp, src/config.hpp, src/config_def.cpp, src/config_def.hpp, src/draw.cpp, src/hcl.hpp, src/i18n.cpp, src/i18n.hpp, src/set_option.cpp, src/spec.cpp, src/spec.hpp, src/tests/spec.cpp, src/thirdparty/microhcl/hcl.hpp, src/thirdparty/ordered_map/LICENSE, src/thirdparty/ordered_map/ordered_hash.h, src/thirdparty/ordered_map/ordered_map.h, src/thirdparty/ordered_map/ordered_set.h, src/ui.cpp
Close #673.
Adds `tsl::ordered_map` as a new dependency and edits `hcl.hpp` to use it instead. Now the declared order inside any HCL object will be the same as the order of iteration of `hcl::Object`.
=> Use tsl::ordered_map instead of std::unordered_map in HCL objects

src/ctrl_inventory.cpp, src/input.cpp, src/lua_env/lua_api.cpp
Close #667.
Allows numbers to roll over in number input prompt. Also adds more validation to the input function.
```lua
local Enums = Elona.require("Enums")
local GUI = Elona.require("GUI")
local Input = Elona.require("Input")
local function make_sandbag(x, y, chara_id)
Item.create(x, y, 733, 1)
local chara = Chara.create(x, y, chara_id)
chara:set_flag(Enums.CharaFlag.IsHungOnSandBag, true)
return chara
end
local function prompt(max)
local result = Input.prompt_number("Which number?", max)
if result then
GUI.txt("Result: " .. result .. " ")
else
GUI.txt("Never mind. ")
end
end
local function handle_chara_damaged(chara)
if not Store.map_local.chara then
return
end
prompt(1) …
```
=> Allow number rollover in number input prompt

doc/api/gui.luadoc, src/lua_env/lua_api.cpp, src/message.cpp, src/util.hpp
Close #666.
Replaces marks in messages by width instead of byte. Japanese characters in UTF-8 could be composed of 3 bytes, causing printing by byte position to drift.
```lua
local Rand = Elona.require("Rand")
local GUI = Elona.require("GUI")
local function message_en()
local text = "\""
for i=0, Rand.rnd(5) do
text = text .. "hmm"
end
text = text .. "♪1\""
GUI.txt(text)
end
local function message()
local text = "「"
for i=0, Rand.rnd(5) do
text = text .. "ふ〜ん"
end
text = text .. "♪1」"
GUI.txt(text)
end
Event.register(Event.EventKind.AllTurnsFinished, message)
Event.register(Event.EventKind.AllTurnsFinished, message_en)
```
=> Replace message mark widthwise instead of bytewise

doc/api/event_eventkind.luadoc, runtime/mods/kiroku/init.lua, src/init.cpp, src/lua_env/event_manager.cpp, src/lua_env/event_manager.hpp, src/lua_env/lua_api.cpp, src/lua_env/lua_api.hpp, src/lua_env/lua_env.cpp, src/lua_env/lua_env.hpp, src/testing.cpp, src/tests/data/mods/test/init.lua, src/tests/lua_api.cpp
- Allows loading of mods inside the `mods` folder besides `core`.
- Allows mods to return an API table at the end of `init.lua`, for declaring public exports.
- Implements `Elona.require` for mods besides `core` (`Elona.require("some_mod", "MyModule")`)
- Adds `AllModsLoaded` callback, for safely calling initialization functions after mods have loaded successfully.
=> [WIP] Load mods besides "core"

src/lua_env/lua_env.cpp
Close #680.
@Ruin0x11 
I haven't read all of your changes well, so could you review the fix is proper or not?
```cpp
enum class mod_loading_stage_t : unsigned
{
not_started,
scan_finished,
core_mod_loaded,
all_mods_loaded,
};
```
I guess `core_mod_loaded` and `all_mods_loaded` imply `scan_finished`.
=> Fix wrong condition checking if all mods have been scanned

src/init.cpp
Change `boost::filesystem::path("save")` to `filesystem::path("save")`.
The former returns relative path from current directory, while the latter returns absolute path based on the executable path.
=> Fix save directory

CMakeLists.txt, runtime/data/scene1.hsp, runtime/data/scene2.hsp, runtime/mods/core/data/music.hcl, src/audio.cpp, src/audio.hpp, src/casino.cpp, src/command.cpp, src/db_music.cpp, src/db_music.hpp, src/dmgheal.cpp, src/elonacore.cpp, src/init.cpp, src/lion.hpp, src/main_menu.cpp, src/proc_event.cpp, src/quest.cpp, src/snail/detail/sdl_impl.cpp, src/testing.cpp, src/variables.hpp
#604.
- Move music definitions to an external file, `music.hcl`.
- Allow playing back any music format that `SDL_Mixer` supports.
- Increase the resolution of audio playback to 44100 Hz.
- Update `scene1.hsp` and `scene2.hsp` to use the data ID format.
- Add definitions of 7 extra songs that are only played during cutscenes.
- Allow music discs to spawn with cutscene-only music.
=> Externalize music as definition files

src/draw.cpp
Close #711.
The color modifier of items used to be applied directly to the item atlas buffer, `1`, because everything item-related resided in buffer `1`, and `set_color_mod()` implicitly acts on the current buffer if none is provided. Now that that isn't the case, the color modifier wasn't being applied to the buffer that was managed by `pic_loader` that acted as the source of the item chip, since it wasn't the one selected with `gsel()`.
=> Apply color modifier to source buffer managed by pic_loader

src/elonacore.cpp
#715. Close #723.
Part of the `mdata` refactoring was incorrect when checking for home departure.
=> Fix check for home departure being of wrong type

runtime/locale/jp/activity.hcl, src/activity.cpp
Remove unnecessary period in JP.
> BEFORE:
> マテリアル: 電気を1個採取した。。(1)
> AFTER:
> マテリアル: 電気を1個採取した。(1)
Fix text color at material spot.
BEFORE:
AFTER:
=> Fix text color at material spot

CMakeLists.txt, src/elonacore.cpp, src/proc_event.cpp, src/proc_random_event.cpp, src/random_event.cpp, src/random_event.hpp, src/variables.hpp
The title was stored in the global variable `s`, but it might be overwritten during an event process.
=> Fix random event's title being empty

doc/api/classes/LuaCharacter.luadoc, runtime/data/lua/enums.lua, runtime/mods/core/exports/eating_effect.lua, src/lua_env/api_manager.cpp, src/tests/lua/classes/LuaCharacter.lua
- Fix wrong function name in Lua.
- `apply_status_ailment` -> `apply_ailment`. The former doesn't exist.
- Implement missing Lua function, `modify_resistance()`.
=> Fix eating effect

src/lua_env/loaded_chunk_cache.hpp, src/lua_env/mod_manager.cpp, src/lua_env/mod_manager.hpp, src/tests/data/mods/test_require_chunks/data/script.lua, src/tests/lua_mods.cpp
Close #731.
- Implement a special version of `require` for use in mods.
+ Mods can load other Lua files, and the results of the load will be cached.
+ Mods cannot load files outside the mod's directory.
=> Implement per-mod require and loaded chunk cache

src/input.cpp
Fix keys not working after using house board.
1. Use[t] house board.
2. Press ESC and select any tile.
3. Exit house design mode.
4. Press two cursor keys at the same frame.
Add missing `await()`.
=> Fix keys not working after using house board

.luacheckrc, doc/api/animation.luadoc, doc/api/classes/LuaPosition.luadoc, runtime/data/script/test_animation.lua, src/activity.cpp, src/animation.cpp, src/animation.hpp, src/command.cpp, src/elonacore.cpp, src/lua_env/api_manager.cpp, src/lua_env/api_manager.hpp, src/magic.cpp, src/proc_event.cpp, src/talk.cpp, src/tests/lua/chara.lua, src/variables.hpp
Close #732.
- Lifts globally used animation parameters into animation class constructors.
- Refactors animations using `character` to use `position_t` instead.
- Removes globals `anix`, `aniy`, `aniref`, `anic`.
- Adds `Animation` Lua API.
- Adds `LuaPosition` API table for `new` constructor (for test script).
A bunch of code cleanup will be enacted after it is merged. (#752, #753)
```lua
local Animation = Elona.require("Animation")
local Enums = Elona.require("Enums")
local Input = Elona.require("Input")
local Rand = Elona.require("Rand")
local LuaPosition = Elona.require("LuaPosition")
local choice = 0
local switcher = nil
local function make_sandbag(x, y, chara_id) …
```
=> Refactor animation parameter/Add Animation API

CMakeLists.txt, runtime/data/lua/handle.lua, src/building.cpp, src/character.cpp, src/character.hpp, src/character_making.cpp, src/dmgheal.cpp, src/elonacore.cpp, src/initialize_map.cpp, src/item.cpp, src/lua_env/handle_manager.cpp, src/lua_env/handle_manager.hpp, src/lua_env/lua_api/lua_api_chara.cpp, src/tests/item.cpp, src/tests/lua_handles.cpp
Close #749.
Adds the missing changes for Lua handle management from #710. This should prevent assertions related to Lua object handles.
=> Add Lua object reference changes from serialization change

src/tests/lua_handles.cpp
Some tests that manipulate characters/items didn't have `start_in_debug_map()` at the beginning, so the required state wasn't initialized first, causing errors.
=> Add start_in_debug_map to certain tests that need it

src/elonacore.cpp
Fix crash when you drop an item and the item is stacked.
1. Start new game.
2. Drop one crim ale.
3. Drop another crim ale.
4. Assertion fails.
=> Fix crash when you drop item

src/calc.cpp
Fix up #745.
Random item colors are different from the previous ones.
=> Fix random item color like potions

runtime/mods/core/data/item.hcl, src/db_item.cpp
Fix up #745.
Fix default item color(`Enums.Color.White`, index 1 -> `Enums.Color.None`, index 0). `White` represents the same color as `None`, but internally have each different value(1 and 0). As the result, an item generated before #745 and an item generated after it do not stack.
=> Fix default item color

runtime/data/lua/handle.lua, src/character.cpp, src/tests/lua_handles.cpp
Close #773.
Adds more checks to handle in-place character relocation caused by change creature magic and related.
The issue was mainly that a temporary character with an empty state was being copied over a valid character, but the corresponding Lua reference was not updated to reflect this.
```lua
local Map = Elona.require("Map")
local function setup()
for i=0,25 do
Chara.create(Map.random_pos(), "core.master_yeek")
end
Item.create(25, 25, "core.rod_of_change_creature", 5)
end
Event.register(Event.EventKind.ScriptLoaded, setup)
```
=> Fix case of Lua reference relocation during "change" mode

doc/api/classes/LuaCharacter.luadoc, doc/api/math.luadoc, runtime/data/lua/init.lua, runtime/data/lua/math_ext.lua, runtime/mods/core/exports/eating_effect.lua, src/lua_env/lua_class/lua_class_character.cpp, src/lua_env/lua_class/lua_class_character.hpp, src/tests/lua/exports/eating_effect.lua, src/tests/lua_api.cpp
Close #775. Close #759.
- Adds missing functions used by `mods/core/exports/eating_effect.lua`.
- Adds sanity check test for `exports/eating_effect.lua`.
=> Add missing functions needed by exports/eating_effect.lua

src/draw.cpp
Close #784.
The assembled card image was copied to `(0, 960+48)` in the work buffer, but if the character image was only 48 pixels tall, the space at `(0, 1008)` would not be cleared as the clearing started from `(0, 960)` and the cleared region was only as tall as the character.
=> Fix overlap of generated card image

src/ui/ui_menu_ctrl_ally.hpp
Not sure why, but the change in https://github.com/Ruin0x11/ElonaFoobar/commit/2b10dfb45be2f03681711b16a0b24531a10eb01c became undone in `ui_menu_ctrl_ally.hpp`.
=> Fix incorrect forward declaration in ui/ (again)

src/talk_unique.cpp
Many dialogue sequences call pieces of code in between dialog messages. This commit makes it clearer where they are called by adding spaces/refactoring pieces of code into functions.
=> Refactor out most inline functions in talk_unique.cpp

src/pic_loader/extent.hpp, src/pic_loader/pic_loader.cpp, src/pic_loader/pic_loader.hpp
Close #806.
Allocate a buffer before the first access to avoid out of range excepion.
=> Fix out of range access

src/activity.cpp
Close #788.
The global variable `ci` was overwritten after `apply_general_eating_effect()` if the character vomited. Saves the previous `ci`(which represents the food) and then restore it.
=> Fix cursed food not being removed

.github/CODE_STYLE.md, .github/CONTRIBUTING.md, Makefile.win
Developers with access to Windows only will currently not be able to run `make format`, so the automated build will not pass if any formatting differences are found. This adds the `make format` command to `Makefile.win`.
=> Add 'make format' command for Windows

runtime/locale/en/config.hcl, runtime/locale/jp/config.hcl, runtime/mods/core/config/config_def.hcl, src/config.cpp, src/config.hpp, src/menu.cpp, src/ui.cpp
Allow player to track up to 10 skills and shows corresponding potential slightly tinted in green if > 100, in yellow if >50 or in red if <=50.
=> Add 7 more tracked skills and potential tinted according to value.

runtime/config.hcl, runtime/mods/core/config/config_def.hcl, src/init.cpp
Close #573.
Add a config option, `run_script_in_save`, that will load startup scripts when a save is loaded, instead of creating a blank map and loading it.
=> Add option to run script over existing save data

CMakeLists.txt
Close #800 .
This change makes rebuilds always copy over the contents of `bin/`, except for `config.hcl`.
=> Modify build system to always overwrite all files except config

runtime/locale/en/config.hcl, runtime/locale/en/ui.hcl, runtime/locale/jp/config.hcl, runtime/locale/jp/ui.hcl, src/set_option.cpp
Close #789.
Allows pressing `*` at the config menu to display config item descriptions.
=> Implement config item description for English

runtime/locale/en/config.hcl, runtime/locale/jp/config.hcl, runtime/mods/core/config/config_def.hcl, src/cell_draw.cpp, src/config.cpp, src/config.hpp
Close #823 
New option:
```
PCC Graphic
Shrinked(Normal)        default
Full-scale
```
Left: shrinked
Right: full-scale
=> Add a option to toggle PCC graphic scale(shrinked/full-scale)

src/wish.cpp
Fix two bugs related to wishing.
> "redemption!!"
When you wished "redemption", your karma changed regardless of whether you were a criminal or not.
> "alias!!"
When you wished "alias", you were able to change your alias regardless of whether you were in wizard mode or not.
=> Fix some wishing

src/elonacore.cpp
Fix departure message.
1. Start a new game.
2. Leave your home.
> You left North Tyris.
The current map name(`North Tyris`) was displayed as the left map name(`Your Home`).
=> Fix the current map name being displayed as the left map name

src/draw.cpp, src/ui.cpp
Close #833 
- Adjust Y position of skill trackers.
- Move pets' HP bars below the skill trackers.
=> Fix overlap between hp bar and skill tracker

src/quest.cpp
Close #835 
Use floating point number, instead of integer.
=> Fix overflow of harvest quest's reward

src/dmgheal.cpp, src/elonacore.cpp, src/item.cpp, src/item.hpp
Close #837 
- Refactor related functions.
- Fix item_cold()'s message.
- Check whether PC can see the character/the position.
- Add "on the ground" to the messages if the destroyed item is placed on the ground.
- Change fireproof blanket's behavior. Now that it does not rely on PC's vision.
- Separate blanket immediately before they work.
- Previously, blankets were separated even if all of your stuffs are fire/coldproof.
=> Fix item_fire() and item_cold()

src/activity.cpp, src/activity.hpp, src/ai.cpp, src/blending.cpp, src/building.cpp, src/cell_draw.cpp, src/character.hpp, src/character_status.cpp, src/command.cpp, src/ctrl_inventory.cpp, src/elonacore.cpp, src/initialize_map.cpp, src/item.cpp, src/magic.cpp, src/menu.cpp, src/random_event.cpp, src/status_ailment.cpp, src/talk.cpp, src/turn_sequence.cpp, src/ui.cpp
Define `struct ContinuousAction` instead of `Character`'s three fields:
- `continuous_action_id`
- `continuous_action_turn`
- `continuous_action_item`
`ContinousAction` has the same layout as the three fields so this change does not affect save data's compatibility.
=> Define struct ContinuousAction

src/ability.cpp, src/ability.hpp, src/calc.cpp, src/calc.hpp, src/elonacore.cpp
Move pieces of formulae into `calc.cpp`. It would be in preparation for the ability to change how certain game formulae are calculated with a mod.
=> Refactor inline formulas in ability.cpp

src/enchantment.cpp
Close #862 
- Rewrites `check_enchantment_filters()`.
- Fixes the condition to add enchantments to ammo.
=> Fix special ammo not being added

runtime/locale/en/item.hcl, runtime/locale/jp/item.hcl, src/i18n.hpp, src/item.cpp
Close #861.
The current interpolation code can only handle a single passed-in argument per function call, in the first argument position. This is due to the use of a variadic argument with a recursive function to format each function call, so only the argument at the head of the variadic arguments is passed in per function. The workaround is to call `itemname` in C++ instead with the second argument and pass the string to the formatter.
Multiple arguments could be supported by moving the I18N functions to Lua (which would be necessary for other reasons).
=> Fix crash of itemname in burning item

src/quest.cpp
#844 
Fixes wrong arguments in quest dialog. The passed arguments are only used in Japanese.
=> Fix wrong arguments in quest dialog

CMakeLists.txt
It is the very cause why v0.2.7 release build failed.
`/MT` flag specified in `CMAKE_CXX_FLAGS` was overridden by `/MD` in release builds for some reason.
=> Add `/MT` flag for release build on Windows

.travis.yml
No tests had been checked on macOS for some reason.
=> Run CI tests on macOS

src/audio.cpp, src/cell_draw.cpp, src/character.cpp, src/command.cpp, src/elonacore.cpp, src/mapgen.cpp, src/mdata.hpp, src/text.cpp
Replaces comparisons between int and MapType with `is_nefia` fucntion.
```cpp
static_cast<int>(mdata_t::MapType::dungeon) <= X && X <= static_cast<int>(mdata_t::MapType::dungeon_castle)
// |
// V
mdata_t::is_nefia(X)
```
=> Reduce static_cast<int>(MapType) by using a helper function

src/animation.cpp
Breaking animation was always drawn even if you can't see there.
Checks PC's vision.
=> Do not play breaking animation if you cannot see there

src/defines.hpp, src/putit.hpp
#895 
- Uses `uint64_t` instead of `size_t`.
- Add conversion between little endian and big endian on saving/loading in BE machine. All data are saved in LE even if the machine runs in BE, in order to make the save portable.
=> Improve serialization portability

src/main_menu.cpp
Close #898.
Fixes shadow of window in selecting save menu.
=> Fix shadow of selecting save window disappearing once you change page

CMakeLists.txt, Makefile, Makefile.win
When you run `make`, and then `make tests`, build fails because `SNAIL_HEADLESS` is a cache variable, which does not change until you explicitly `unset` and `snail` library is built in SDL mode.
This pull request provides these make targets.
- `make build`: Build the normal executable.
- `make tests`: Build test runner.
- `make bench`: Build benchmark runner.
- `make`: Build the target previously built. You may usually `make` this target.
=> Overwrite SNAIL_HEADLESS flag if you specify WITH_TESTS=OFF

src/item.cpp
Close #912.
Check if the items is on the ground or in your inventory.
=> Do not show message "something falls down" if the item is on the ground

src/map_trainer_skills.cpp
It was accidentally set to call `trainer_skills_yowyn()`.
=> Fix trainer_skills_vernis

src/dmgheal.cpp
#937.
The text was being displayed when the character's state was already `empty`. When the state is set to `empty`, the corresponding Lua reference is removed, but this causes localized text using Lua references in functions to fail since a blank reference was passed. It is done this way since characters with `empty` state can be overwritten by another character at some other time, but there are likely many instances in the code where a character with `empty` state is still passed around when it is known to be referencing the same character as before.
As a workaround, make sure the state is `pet_dead` first, which creates another Lua reference first.
=> Fix impression modify I18N error

src/elonacore.cpp
Scenes will currently not fade to black because the default color of `boxf` is transparent instead of opaque.
=> Fix scene fade out

src/ctrl_inventory.cpp
`switch_mode_2` mistakenly triggered the behavior of `identify` in the inventory as it is checked for in two places.
=> Fix switch_mode_2 action in inventory being duplicated

CMakeLists.txt, Makefile, Makefile.win
Adds some options to the build process to speed up the incremental build on Linux and macOS.
- If either of `GNU gold` or `lld` are available, use one as the linker.
- On Linux, enable split DWARF.
Here is a comparison of the time taken for an single-file incremental build. Tested on `linux 4.16.9-1` with `clang 7.0.0`/`lld`.
Before:
```
~/build/elonafoobar % /usr/bin/time -v make
cd bin; cmake .. ; make -j24
...
User time (seconds): 13.58
System time (seconds): 1.84
Percent of CPU this job got: 100%
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:15.35
...
Maximum resident set size (kbytes): 618892
```
After:
```
~/build/elonafoobar % /usr/bin/time -v make
cd bin; cmake .. ; make -j24
...
User time (seconds): 7.53
System time (seconds): 1.74
Percent of CPU this job got: 115%
Elapsed (wall …
```
=> Speed up incremental build time on Linux/macOS

runtime/mods/core/data/chara_chip.hcl, src/db_chara_chip.cpp, src/db_item_chip.cpp, src/draw.cpp, src/draw.hpp, src/pic_loader/pic_loader.cpp, src/pic_loader/pic_loader.hpp
#957.
- Fix `pic_loader` not returning the correct buffer when adding a new one.
- Fix ID collisions in `pic_loader` lookup by making IDs fully qualified. (`core.putit -> core.chara_chip:core.putit`)
+ The chip for `dragon` (`core._228`) collided with an item chip with the same ID.
+ If multiple images are to be supported per data type, more specific naming may be needed.
- Add missing ID names for race-default character chips.
=> Fix various pic_loader issues

src/ui.cpp
Close #966.
Moves the skill tracked potential slightly to the right so it does not overlap in both languages.
Japanese:
English:
=> Adjust position of skill tracked potential

src/ui/ui_menu_crafting.cpp
Close #933.
Fixes the text color of entries in the crafting menu.
=> Fix item names in crafting menu being colored wrong

src/input_prompt.cpp
The size of selection key's image is 24x18, but wrongly drews it in 24x24.
=> Remove graphics garbage of selection keys

src/lua_env/data_manager.hpp
Fixes forward declaration of `class ModInfo` to fit actual definition, `struct ModInfo` in order to suppress warning.
=> Fix forward declaration to fit actual definition: class -> struct

src/shared_id.hpp
=> Suppress unused variable warning due to Boost.Flyweight

runtime/config.hcl, runtime/locale/en/config.hcl, runtime/locale/jp/config.hcl, runtime/mods/core/config/config_def.hcl, src/config/config.cpp, src/config/config.hpp, src/ctrl_inventory.cpp
Close #916.
Add the option to skip confirm prompt to buy or sell items at town shops, `foobar.skip_confirm_at_shop`(Default: false, as before).
=> Add option to skip confirm at shop

src/defines.hpp, src/shared_id.hpp
Close #996 
Encloses pragma to suppress "unused variables" warning reported by Clang with `#ifdef` directive in order to suppress "unknown pragma" warnings output by other compilers like GCC or MSVC.
=> Add #if directive to suppress warnings

src/elonacore.cpp, src/food.cpp, src/food.hpp, src/initialize_map.cpp, src/variables.hpp
Close #958.
This bug also happens in vanilla and there are few variants that have fixed it except for recent MMAh.
```
// pseudocode:
i = (The date and time in-game)
for food in items:
if (the expiration date) < i:                    # (*0)
The food gets rotten.
if you believe in Kumiromi:
i = (The item's subcategory)             # (*1)
if a third:
You extract seed(s) from the food.
i = (The date and time in-game)      # (*2)
```
The variable `i` is modified at line (*1) and restored at line (*2), but (*2) is executed only if you extract seeds. As a result, when a food gets rotten and you don't extract seed from it, the variable `i` become
an invalid value and then, the condition (*0) fails to determine whether a food should get rotten or not.
=> Fix food not getting rotten sometimes if you believe in Kumiromi

CMakeLists.txt
=> Delete src/get_random_item_id.cpp, no longer used

src/config/config_menu.hpp, src/keybind/input_context.hpp, src/keybind/keybind.cpp, src/snail/application/sdl.cpp, src/snail/touch_input/headless.cpp, src/snail/window/headless.cpp, src/tests/lua_callbacks.cpp, src/tests/lua_handles.cpp, src/ui/ui_menu_crafting.cpp
- Unused parameters; add `void` casting.
- Unused variables; delete them.
- No virtual destructor; add it.
=> Reduce compiler warnings

runtime/config.hcl, runtime/locale/en/config.hcl, runtime/locale/jp/config.hcl, runtime/mods/core/config/config_def.hcl, src/config/config.cpp, src/config/config.hpp, src/elonacore.cpp
Close #1020.
Adds new option "foobar.skip_overcasting_warning" to skip the warning prompt saying "You are going to over-cast the spell. Are you sure?"
By default, it is set to false, which is compatible with vanilla's behavior.
=> Add option "foobar.skip_overcasting_warning"

src/data/types/type_chara_chip.cpp, src/data/types/type_item_chip.cpp
Close #1025.
Insert missing colon separator between data type ID and data ID.
Example:
`core.chara_chipcore.putit` => `core.chara_chip:core.putit`
=> Fix inner ID of item chip and character chip

src/keybind/keybind.cpp
=> Do not output meaningless keybind error when no input is passed

runtime/mods/core/data/map.lua
The previous position, (37, 20), is not an accessible cell and the
actual position varies in each save data. In most cases, the actual
position become (38, 20) or (37, 21), but sometimes the crypt moves far
away or moves several times when a diastrophism occurs.
The new position, (38, 20), is the same as MMAh's. Thanks to the author
of MMAh and reporters of this bug.
Link to the post by the author of MMAh: http://jbbs.shitaraba.net/bbs/read.cgi/game/58103/1534584992/509
=> Move the position of the crypt of the damned right

src/ui/ui_menu_ctrl_ally.cpp
Close #1044.
The cause of the bug is that the return value of `ctrl_ally`, a function to choose one of your allies, may be 0, which means the player character. Selling a slave deletes the sold character, so in this case, you are deleted.
This pull request also resolve these errors:
- Cannot call back your allies from a bartender.
- Cannot command your allies to stay in your home.
- Cannot investigate your allies' stats.
=> Fix not being able to choose correct ally

src/character.cpp, src/item.cpp, src/tests/lua_handles.cpp
Close #1050.
Before, `item_copy()` and `chara_copy()` could copy into slots occupied by Lua references whose concrete object had already been removed, but where the reference is still valid. This is due to the changes in e4ef187f causing Lua references to not be invalidated at the point of removal, only at the exact moment a new object occupies a previously invalidated slot.
The solution is to check before copying whether the reference in the item/character slot is valid, and to clear it before copying.
There are probably other bugs of this kind where a stale reference is not cleared before performing an action that would create a new handle in the same slot.
=> Fix crash from using Cat's Cradle

src/pic_loader/pic_loader.hpp
Close #957.
Fix skyline packing algorithm.
```diff
- x >= 0 && y >= 0 && x + w < width && y + h < height;
+ x >= 0 && y >= 0 && x + w <= width && y + h <= height;
```
E.g.,
x = 50
w = 100
width = 150
The rectangle apparently has enough width.
```diff
+ --i;
```
Since erase() method changes index, needs to decrement the index in
order to shrink skylines again based on the current skyline (which was inserted just now).
=> Fix skyline packing algorithm

src/elona/dialog/dialog_data.cpp, src/elona/dialog/dialog_data.hpp, src/elona/dialog/dialog_decoder.cpp
Close #892.
Before, `DialogData::is_cancelable_now()` always returns false, and now,
it returns `DialogData::is_cancelable` given by dialog definition data.
The function's name has "now", but currently returns the same value.
This limit will be abolished in the future.
The new field is optional, and set to true by default as many vanilla
dialog window (currently hard-coded) are.
=> Add is_cancelable to DialogData, the flag whether you can cancel a talk

src/elona/ctrl_file.cpp
Close #1066.
`CellData::unpack_from()` was not called although `map` was updated.
=> Fix regenerated map not being rebuilt

src/elona/Android.mk, src/elona/CMakeLists.txt, src/elona/elonacore.cpp, src/elona/init.cpp, src/elona/initialize_map.cpp, src/elona/message.cpp, src/elona/message.hpp, src/elona/message_log.cpp, src/elona/message_log.hpp, src/elona/ui/ui_menu_message_log.cpp, src/elona/ui/ui_menu_message_log.hpp
Close #913.
- Limit the number of the message log lines to 1000.
- The upper limit should be configurable.
- Add key mappings to scroll message log by page.
- PageUp or Left: scroll 1 page up(to older)
- PageDown or Right: scroll 1 page down(to newer)
- Home: go top(oldest)
- End: go bottom(latest)
=> Enhance message log

src/elona/input.cpp, src/elona/input.hpp
Close #1065.
This bug also happens in other kinds of list selection menu, i.e., routines which `get_selected_item()` is called from.
Check whether selection key is out of range or not. Selection key, in this case, means Enter and `a`, `b`, `c`, ..., `p`.
Before, you could select 5th item even if there were only 4 items in the current list menu. #1065 reported special case of that, you can select 1st item when there is no items in the inventory.
=> Fix selection key can select out-of-range choice

.travis.yml, appveyor.yml
#1064 
Add `--durations=yes` option to output execution time on testing for the purpose of detecting the bottleneck of slow Appveyor execution.
=> Measure the elapsed time on testing in CI

src/elona/ctrl_file.cpp, src/elona/initialize_map.cpp, src/elona/map.cpp, src/elona/map.hpp, src/elona/talk_unique.cpp
Close #1085.
On map re-construction, the corresponding map file (`map/*.map`) is partly loaded (`map` data has 10 fields, but in this case, only updates 3 of 10.) However, `CellData::unpack_from()` function updated the rest 7 fields. It causes data mismatching.
=> Fix Christmas festival items in Noyel not being removed completely

runtime/data/lua/handle.lua, src/tests/lua_handles.cpp
Close #1084.
Fix wrong item name after trading items for "I want it!" quest. This pull request does not delete completely `Handle.swap_handles()` for some future use.
Example:
- Item A: the item you have (index 0), now, it's a scroll of faith.
- Item B: the item the NPC has and you want (index 3000), now, it's a raw ore of rubynus.
Before `Handle.swap_handles()` is called, the handle table is like this:
```lua
handles_by_index["LuaItem"][0].__uuid == "foo" -- "foo" is, of course, actually some valid UUID.
handles_by_index["LuaItem"][3000].__uuid == "bar"
refs["LuaItem"]["foo"] == pointer to Item A
refs["LuaItem"]["bar"] == pointer to Item B
```
The previous implementation of `Handle.swap_handles()` swaps these UUIDs:
```lua
-- This is different from the actual code, but does the same …
```
=> Fix wrong item name after trading items for "I want it!" quest

runtime/locale/en/keybindings.hcl, runtime/locale/jp/keybindings.hcl, src/elona/keybind/keybind_actions.cpp, src/elona/turn_sequence_pc_actions.cpp
Close #1083.
Instead of `auto_action`, use `enter` for the same effect. This allows keys bound to `Enter` to have the automatic action and reduces confusion.
=> Remove `auto_action` action and use `enter` instead

src/elona/access_item_db.cpp, src/elona/activity.cpp, src/elona/blending.cpp, src/elona/calc.cpp, src/elona/command.cpp, src/elona/ctrl_inventory.cpp, src/elona/elonacore.cpp, src/elona/enchantment.cpp, src/elona/equipment.cpp, src/elona/food.cpp, src/elona/item.cpp, src/elona/item.hpp, src/elona/item_load_desc.cpp, src/elona/itemgen.cpp, src/elona/magic.cpp, src/elona/quest.cpp, src/elona/talk_npc.cpp, src/elona/turn_sequence.cpp, src/elona/ui.cpp, src/elona/wish.cpp, src/tests/serialization.cpp
Like `cbit()`, make methods for each `ibit()` and `ibitmod()` calls.
- ibit(1, x): is_acidproof
- ibit(2, x): is_fireproof
- ibit(4, x): has_charge
- ibit(5, x): is_precious
- ibit(6, x): is_aphrodisiac
- ibit(7, x): has_cooldown_time
- ibit(8, x): is_blessed_by_ehekatl
- ibit(9, x): is_stolen
- ibit(10, x): is_alive
- ibit(12, x): is_quest_target
- ibit(13, x): is_marked_as_no_drop
- ibit(14, x): is_poisoned
- ibit(15, x): is_eternal_force
- ibit(16, x): is_showroom_only
- ibit(17, x): is_handmade
=> Make methods for each ibit() and ibitmod() calls

src/elona/init.cpp, src/elona/input.cpp, src/elona/input.hpp, src/elona/keybind/input_context.cpp, src/elona/turn_sequence.cpp, src/elona/turn_sequence_pc_actions.cpp, src/elona/ui/ui_menu_character_sheet.cpp
Close #1056.
Use the `key` global as it was used before for certain key detection edge cases that are difficult to handle through the keybinding system.
- Angband easter egg.
- Usage of 'p' key in character sheet.
=> Use "key" global for some edge cases difficult to handle in keybinds

src/elona/autopick.cpp
#1106 and #1096 didn't conflict with each other, but #1096's change newly added `ibit()` calls which were removed in #1106.
=> Fix broken build: replace ibit() with new methods

src/elona/magic.cpp
Close #1108 
Check whether buff's id is valid, that is, not zero, before calling `BuffDB::operator[]`.
=> Fix reference to undefined buff

src/elona/blending.cpp, src/elona/input.cpp, src/elona/input.hpp, src/elona/input_prompt.cpp, src/elona/input_prompt.hpp
Close #1124 
Delete legacy global variable, `TODO_show_prompt_val`, and use return value of `PromptWithNumber::query()` instead.
=> Fix prompt with number not returning input number

CMakeLists.txt, README-jp.md, README.md, src/snail/CMakeLists.txt, src/snail/filedialog.cpp, src/snail/filedialog.hpp, src/snail/filedialog/headless.cpp, src/snail/filedialog/sdl.cpp, src/thirdparty/nfd/.gitattributes, src/thirdparty/nfd/CMakeLists.txt, src/thirdparty/nfd/LICENSE, src/thirdparty/nfd/common.h, src/thirdparty/nfd/include/nfd.h, src/thirdparty/nfd/nfd_cocoa.m, src/thirdparty/nfd/nfd_common.c, src/thirdparty/nfd/nfd_common.h, src/thirdparty/nfd/nfd_gtk.c, src/thirdparty/nfd/nfd_win.cpp, src/thirdparty/nfd/nfd_zenity.c, src/thirdparty/nfd/simple_exec.h
#132
Original: https://github.com/mlabbe/nativefiledialog
- Linux: use GTK
- macOS: use Cocoa
- Windows: use Win32 API
- Android: not supported (but Java API is fully available if you want)
- Headless environment: not supported (and of course unnecessary)
Currently, this API is not used. I have a plan to implement #132, adding installer, by using it. In addition, it will be needed for some mods.
=> Add experimental file dialog support

Makefile, src/elona/ui.cpp, src/snail/filedialog/sdl.cpp
Close #1131 
Restore the draw color changed by `ui_draw_caption()`.
=> Fix text color in character making

runtime/data/lua/handle.lua
Close #1134 
The assert() asserts that the destination slot has to be empty, but it
is wrong in the current implementation.
=> Delete wrong assert() in Handle.relocate_handle()

src/elona/keybind/keybind_actions.cpp
Close #1149.
- Fix default key binding of x and X.
- `x` -> quick inventory
- `X` -> examine
- Change the order of `x` and `X`.
- Before:
- quick menu
- zap
- examine
- quick inventory
- After:
- quick menu
- zap
- quick inventory
- examine
=> Fix default key bindings of x and X

appveyor.yml
#1115 is not complete. Delete `log.txt` file and `save\` directory before deployment.
=> Delete unnecessary files before deployment

src/elona/building.cpp
1st comes first, 10th, last. I think that most "rankings" are sorted in ascending order like this:
=> Reverse heirloom ranking

runtime/locale/en/main_menu.hcl, runtime/locale/jp/main_menu.hcl, src/elona/Android.mk, src/elona/CMakeLists.txt, src/elona/browser.cpp, src/elona/browser.hpp, src/elona/elona.hpp, src/elona/main_menu.cpp, src/elona/main_menu.hpp, src/elona/menu.cpp, src/elona/std.cpp, src/elona/variables.hpp
"View the Homepage" in the main title menu was not implemented before in this variant. In addition, vanilla's (and most variants other than foobar) link to Elona's website has broken. This pul request changes the menu item to "About" which shows more detailed information.
Japanese
English
- Vanilla Elona Homepage
- Open the website, http://ylvania.org/jp or http://ylvania.org/en.
- Elona foobar Homepage
- Open the website, https://elonafoobar.com.
- Elona foobar Changelog
- Format CHANGELOG.md or CHANGELOG-jp.md and show it.
- License
- Show LICENSE.
- Credits
- Show CREDITS.
The current implementation only shows Elona foobar's LICENSE and CREDITS.
=> Change View Homepage in main menu to About

tools/incver.py
It is internally used by me, but I think there is no reason not to publish it. To see usage, run `./tools/incver.py --help`. As you can see, it requires `python3`.
=> Add utility to increment foobar's version

runtime/mods/core/data/map.lua, src/elona/area.cpp, src/elona/data/types/type_map.cpp, src/elona/data/types/type_map.hpp
#1095
Fix crash when you Return if there are some random nefias. Map data of random nefia, map id 8, was missing, and it caused crash on Returning.
=> Fix crash when you Return

src/elona/lua_env/lua_console.cpp, src/elona/lua_env/lua_console.hpp
#984. Close #1103.
Fix interpretation of Lua in the Lua console. (It was missing a pass by reference.)
=> Restore default environment of Lua console

CMakeLists.txt
The macro was defined in Linux and macOS regardless of the build type.
=> Do not define "DEBUG" in release build

src/elona/menu_quick_menu.cpp
Close #1163 
- Do not use global variable `t`, and instead use member variable `_t`.
- Fix wrong blend mode.
=> Fix quick menu not shining

src/elona/audio.cpp, src/elona/config/config.cpp, src/elona/config/config.hpp, src/elona/ctrl_file.cpp, src/elona/data/lua_lazy_cache.hpp, src/elona/i18n.hpp, src/elona/keybind/keybind.cpp, src/elona/log.cpp, src/elona/log.hpp, src/elona/lua_env/api_manager.cpp, src/elona/lua_env/event_manager.cpp, src/elona/lua_env/lua_api/lua_api_debug.cpp, src/elona/lua_env/lua_enums.hpp, src/elona/lua_env/mod_manager.cpp, src/elona/save.cpp, src/elona/save_update.cpp, src/elona/std.cpp, src/elona/testing.cpp, src/main.cpp, src/tests/serialization.cpp
- Delete unused log: they were  for debugging, but no longer used.
- Change usage of `ELONA_LOG` macro.
- Before: `ELONA_LOG(x << y << z)`
- After: `ELONA_LOG(tag) << x << y << z`
- Add `ELONA_WARN()`, `ELONA_ERROR()`, `ELONA_FATAL()` for serious errors.
- Add tag and change log format.
- Example: "INFO  [Lua.Mod] Found mod core"
<details>
```
INFO  [System] Elona foobar version 0.3.3 (db6faf65), compiled on Darwin-18.2.0 at 2019-01-18T19:11:20Z
INFO  [Config] Set: core.config.screen.display_mode to "800x600@60Hz"
INFO  [Config] Set: core.config.language.language to "__unknown__"
INFO  [Config] Set: core.config.game.default_save to ""
INFO  [Config] Set: core.config.game.default_save to ""
INFO  [Config] Set: core.config.screen.sound to true
INFO  [Config] Set: core.config.screen.music to …
```
=> Improve ELONA_LOG() macro and output well-formatted logs

src/elona/text.cpp
=> Fix {sex} tag being always substituted by male

src/elona/ui.cpp, src/elona/ui/ui_menu_game_help.cpp, src/elona/ui/ui_menu_game_help.hpp
Close #1173.
Fix game help text being blurred by drawing background every time.
- Performance is improved at some degree. The bottleneck is `gmes()` function, but it is difficult to optimize it because the function is also used in other places.
- At least in my machine, the performance hit has been resolved in Japanese mode. In English mode, `gmes()` still slows down the performance.
=> Fix game help text being blurred

runtime/locale/en/magic.hcl, runtime/locale/en/misc.hcl, src/elona/elonacore.cpp
Close #1178.
#1140
- Fix typo: "if forbidden" -> "is forbidden".
- Fix the response to the prompt "Returning while taking a quest is forbidden. Are you sure to return?" being wrongly handled.
- The prompt is also shown when you *escape* during an escort quest, but the result is dealt with correctly.
=> Fix returning prompt

src/elona/data/types/type_character.hpp, src/elona/elonacore.cpp, src/elona/initialize_map_types.cpp, src/elona/talk_unique.cpp, src/elona/turn_sequence.cpp
The previous name did not express correct meaning. The creature who has
the flag will not be attacked by others. E.g., putits Lomias releases,
\<Poppy\>.
=> Rename Character::does_not_search_enemy -> is_not_attacked_by_enemy

src/elona/ui/ui_menu_feats.cpp
Close #1194.
Previous switching keys (`z` and `*`) were different from vanilla (`z`, and `x`). Fixes it.
=> Fix "x" key in feat menu not working

src/elona/main_menu.cpp
Close #1204
-  We will set the fixed text width and English font size on the main_menu>about>license page and main_menu>about>credits page.
=> fix License & Credit texts extending outside

CMakeLists.txt
Because these profiles were not removed before testing, some test cases failed in local environment.
=> Remove profile/testing and profile/default before testing

src/elona/config/config.cpp, src/elona/lua_env/mod_manifest.cpp
To build error message, `boost::fiilesystem::path::string()` function was used before, but this function is not appropriate for this case. Because Windows encodes filepath in UTF16, `path::string()` function, which returns `std::string`, i.e., a sequence of `char`, cannot represents native filepath on Windows (UTF16), required 2 bytes to encode. If the filepath contains multibyte characters, `path::string()` attempts to encode its native form in *system-dependent encoding*. For example, if your Windows is running in Japanese language, `path::string()` returns CP932 (codepage 932, Japanese legacy encoding) string. The encoding is incompatible with UTF8, so cannot be concatenated with UTF8 text which Elona foobar mainly uses. This commit fixes the bug to use `filepathutil::to_utf8_path()` …
=> Fix mojibake in error message if filepath contains multibyte characters

runtime/profile/_/mod/core/data/asset.lua, src/elona/config/config.cpp
Close #1228.
The cause is that asset `core.asset#core.lang` has not been loaded when language selection menu is displayed to user. So do not use the image in the menu, and draw text via `mes()` function instead. This change also helps us to add new language support. The language options are still hard-coded now.
=> Fix segmentation fault on launching

src/elona/keybind/input_context.cpp
You cannot run even when you press Shift key in a certain configuration:
Condition:
- scroll: Yes
- scroll when running: No
- running wait: 3 wait
This bug also occurs in vanilla. The original bug report was posted to [MMAh's development thread](http://jbbs.shitaraba.net/bbs/read.cgi/game/58103/1551181700/29).
`keybd_wait` was fixed to 100,000 when you press shift key. Since 100,000 is
not a multiple of 3, the if condition which determines whether you are
about to run or not, `keybd_wait % run_wait == 0`, is always false.
With this change, `keybd_wait` will be incremented properly.
Because the cause is that 100,000 is not a multiple of 3, this bug can be reproduced with other prime number like 7 wait.
=> Fix being unable to run in a certain configuration

Makefile, tools/docgen/src/main.rs
`.ldoc` files did not have a line break at the end of file before. It have generated more unnecessary diff. Fixes `tools/docgen`, and insert EOL.
=> Fix .ldoc files not having a line break at the end of file

src/elona/ui/ui_menu_game_help.cpp, src/elona/ui/ui_menu_game_help.hpp
#1224.
Now it will only be redrawn if a page update happens. This could be generalized to other menus also.
=> Decreate resource usage of help screen

CMakeLists.txt, runtime/profile/_/mod/kiroku/mod.hcl, src/elona/lua_env/mod_manager.cpp, src/elona/lua_env/mod_manifest.cpp, src/elona/lua_env/mod_manifest.hpp, src/elona/semver.hpp, src/tests/data/registry/chara/mod.hcl, src/tests/data/registry/chara_defaults/mod.hcl, src/tests/data/registry/chara_duplicate_key/mod.hcl, src/tests/data/registry/chara_invalid_enum/mod.hcl, src/tests/data/registry/chara_portrait/mod.hcl, src/tests/data/registry/item/mod.hcl, src/tests/lua_mods.cpp, src/tests/semver.cpp, src/util/either.hpp, src/util/range.hpp
Introduced version-based mod dependencies. Detailed specification is inspired by Ruby Gemfile's format and Semantic Versioning. However, it is not exactly the same as either Gemfile or Semantic Versioning.
*Version* consists of tree parts, major, minor, and patch. E.g., `1.0.0`, `3.1.4`, `10.20.30`. Each part must be positive, and less than 100.
*Version requirement* is a pair of *operator* and version. Operator specifies matching algorithm, for example, `Operator::any`, `Operator::equal`, and `Operator::less_than`.
> Example:
>
> Assumes that the version is `2.3.4`. The version satisfies these requirements:
> - `*` and `` (empty string).
> - `= 2.3.4`.
> - `= 2.3`.
> - `< 3`
> - `< 2.4`
> - `>= 2`
> - `> 2.3.1`
> - `> 2.2.0, != 2.3.1`
> - `>= 2.2.0, < 2.5`
=> Implement version-based mod dependencies

doc/examples/life.lua, doc/topics/README.md, src/elona/CMakeLists.txt, src/elona/elonacore.cpp, src/elona/initialize_map.cpp, src/elona/keybind/input_context.cpp, src/elona/keybind/input_context.hpp, src/elona/keybind/macro_action_queue.cpp, src/elona/keybind/macro_action_queue.hpp, src/elona/lua_env/lua_api/lua_api_input.cpp, src/elona/lua_env/lua_api/lua_api_input.hpp, src/elona/lua_env/lua_api/lua_api_map.cpp, src/elona/lua_env/lua_api/lua_api_map.hpp, src/elona/lua_env/lua_class/lua_class_character.cpp, src/elona/lua_env/lua_class/lua_class_character.hpp, src/elona/mapgen.cpp, src/elona/variables.hpp, src/tests/lua/map.lua
- Add some APIs needed for pathfinding. With this, mods implementing autoexplore can be created.
- Remove `Map.bound_within`.
- Replace `Map.can_access` with `Map.is_blocked`.
=> Add macro API and related input/map APIs for pathfinding

src/elona/elonacore.cpp
When you move your cursor to (0, 0) in the current map on housing,
the top right tile flickers, and the position of the highlighting square
moves to the cell you are standing.
It also occurs in vanilla.
The solution is very ad-hoc, but it works.
=> Fix flickering on house designing

src/elona/input_prompt.cpp
Close #1225.
Prompt did not clear key repeat state. As a result, when you cast Return
spell by pressing [b] in the spell menu, the second town in the prompt
was immediately selected.
=> Fix prompt not clearing key repeat state

runtime/mod/core/data/item.hcl
Close #1259
strawberry: 99999 (others) -> 57004 (fruits)
hero_cheese: 57004 (fruits) -> 99999 (others)
rabbit_tail: 57004 (fruits) -> 99999 (others)
The bug report was originally reported to MMAh, and MMAh fixed other items' subcategory as well, but I don't change them other than the above three.
cf. https://twitter.com/ki_foobar/status/1121405431203545088
=> Fix strange item's subcategory

doc/api/chara.luadoc, doc/api/classes/LuaMapGenerator.luadoc, doc/api/item.luadoc, doc/api/registry.luadoc, src/elona/lua_env/lua_api/lua_api.cpp, src/elona/lua_env/lua_class/lua_class.cpp, tools/docgen/src/main.rs
Close #ISSUE.
According to the actual behavior, Rust's clang module may expand `#include` macros before analysis. As a result, files which do not have `@luadoc` magic comment (namely `lua_api/lua_api.cpp` and `lua_class/lua_class.cpp`) were not skipped, and unnecessary luadoc files
were generated. This commit adds `@noluadoc` directive to explicitly state this file does not have any documentation and prevent unnecessary luadoc files from being generated.
=>  Add @noluadoc directive to suppress unnecessary document generation

src/snail/backends/sdl/audio.cpp
These constants are defined, but unused.
- `max_volume`
- `temporary_channels_head`
- `temporary_channels_size`
=> Delete unused constants

runtime/mod/core/data/asset.lua, src/elona/casino_card.cpp
Close #1177.
- Fix #1177. Move card assets to other coordinate.
- Fix this glitch:
Screenshot A (before the commit)
Screenshot B (after the commit)
When you feel bad feeling about the card, you can change it. The trashed card (3rd one) in "Screenshot A" has small black garbage at the corners. The 5th card which is about to be trashed in "Screenshot B" does not.
=> Fix casino card glitch

src/elona/command.cpp
Close #1296 
It is very complicated to deal with item handles, but anyway it works now. Since `Item::set_number()` calls `cell_refresh()` internally, item position should be updated before the call of `Item::set_number()`
=> Fix bug that ghost of monster ball appears

src/elona/ui.cpp
#1289 
There are several rain at the the top left (0, 0). This pull request is fixing it.
Same as the change of b7a7cedb6cde0562dbaed984ab9637361e27dc4a
=> Don't render particles of rain and hard rain's effect at (0, 0)

src/elona/lua_env/lua_api/lua_api_input.cpp
Close #1295.
There are 4 overloaded `Input.prompt_dialog()`, and the implementation of `LuaApiInput::prompt_dialog_with_chip()` and `LuaApiInput::prompt_dialog_with_chip_impress()` were different from other two for some reason. Now, the four variations behave in similar ways.
=> Fix Input.prompt_dialog's overloads

src/elona/save_update.cpp
v0.4.0's save cannot be update to the latest (v0.4.1) properly.
Because update from v8 to v9 and from v9 to v10 were not applied to
shop*.s2, in update from v10 to v11, these files were migrated. However,
shop*.s2 files which were saved in Elona foobar v0.4.0 as valid format
do not require extra migration. As a result, unnecessary migration for
these files broke them and caused errors. Since this commit, foobar
checks whether the corresponding mod_*.s2 files exist and the shop*.s2
file requires migration or not. If not, foobar skips the file.
=> Avoid unnecessary migration

src/elona/initialize_map_types.cpp, src/elona/mapgen.cpp, src/elona/mapgen.hpp
Close #1303 
Change the way to check whether you are standing on snow tile or not (see `map_get_field_type` function). It is dirty solution, but works at least now. It should be rewritten in a better way in the future.
=> Fix snow field not generated

runtime/data/script/kernel/ush.lua, runtime/data/script/kernel/ush/execute.lua, src/elona/lua_env/console.cpp
#983 
- Don't output quotation when the result is string.
- Don't call `inspect()` for tables, and output them in more human-friendly way.
- Fix "Did you mean?" feature not working.
- Add missing period.
=> Improve console output

src/elona/activity.cpp
Maybe, the global variable `feat` was overwritten by plants. Call `cell_featread()` immediately before routine of searching material spot.
=> Fix that you fail to search material spot if there are growing plants

runtime/mod/core/data/map/static.lua, src/elona/initialize_map_types.cpp
Fix #1313 
Port `_init_map_puppy_cave()`, native C++ function, to Lua and remove the C++ one.
=> Move routine for creation of Poppy to Lua side

src/elona/magic.cpp
Autosaving when NPC drinks a potion of potential is unpredictable and surprising.
=> Don't autosave when NPC drinks potion of potential

src/elona/activity.cpp, src/elona/elonacore.cpp
#1315 
- Fix 'You find no target.' not shown.
- Add missing argument to `locale.misc.shakes_head`.
- Fix wrong function: `i18n::s.get` -> `i18n::s.get_enum`.
=> Fix various text error

src/elona/ui/ui_menu_npc_tone.cpp
Check whether `profile/<current profile>/user/talk` exists or not before trying to iterate over the folder.
=> Check whether user/talk direcotry exists or not to avoid crash

src/elona/lua_env/lua_api/lua_api_input.cpp, src/elona/talk.cpp
Neutral NPCs like Gwen usually won't listen to you, but in v0.4.2, you can talk to such NPCs.
Check the return value of `talk_setup_variables()`, and if false, return immediately without showing dialog window.
=> Fix being able to talk to neutral NPCs

src/elona/elonacore.cpp
Close #1321.
Call `item_separate()` before you drink.
=> Fix that stacked wells dry out at the same time

src/util/filepathutil.cpp, src/util/filepathutil.hpp
Close #1325.
wcstombs() takes a multibyte character buffer (output), a wide character
buffer, and the length of the output buffer. However, actually, the
length of *wide character buffer* was passed to. Due to that,
get_executable_path() returns a shorter path than the actual one on
Windows. Now, the function does not convert wchar_t* to char* and
returns internal representation on each OS. On Windows, it is UTF-16,
wchar_t*. (Strictly speaking, C++ specification does not say wchar_t* is
encoded in UTF-16 but Windows does so.)
=> Fix get_executable_path() on Windows

src/elona/lua_env/mod_manager.cpp
Close #1327.
Call `EventManager::trigger()` immediately after `ModManager::stage_` is set to `all_mods_loaded`.
=> Fix "core.all_mods_loaded" event not being fired

src/elona/activity.cpp, src/elona/casino.cpp, src/elona/command.cpp, src/elona/elonacore.cpp, src/elona/magic.cpp, src/elona/proc_event.cpp, src/elona/quest.cpp, src/elona/save.cpp, src/elona/save.hpp, src/elona/turn_sequence.cpp, src/elona/variables.hpp, src/elona/wish.cpp
```cpp
autosave = 1 * (game_data.current_map != mdata_t::MapId::show_house)
```
Replace this line which appeared many times with single function call. Also remove a global flag, `autosave`.
=> Refactor autosaving: remove global flag, instead call function

src/elona/ui/ui_menu_mod_info.cpp, src/elona/ui/ui_menu_mod_info.hpp
Now, foobar finds these file in a mod folder, and show found one.
- README.md
- README.markdown
- README.txt
- README
=> Add README's filename variants in mod details menu

src/elona/dmgheal.cpp
Atomic bomb's damage is no element, but text color of the damage popup was colored in purple.
⬇️
=> Fix text color of damage popup of atomic bomb

src/elona/ctrl_inventory.cpp
[vanilla bug]
When you present gift to someone,
- [to npc/to ally] Your burden state won't be refreshed.
- [to ally] You cannot give other items continuously.
- [to npc] The game turn does not pass.
- [to ally] When you press `x`, opening inventory, the ally's [G]ive menu is shown.
See this page for details: [ElonaFoobar/bugfixes](https://elonafoobar.github.io/bugfixes/#%E3%83%9A%E3%83%83%E3%83%88%E3%81%AB%E3%81%8A%E3%81%BF%E3%82%84%E3%81%92%E3%82%92%E6%B8%A1%E3%81%97%E3%81%9F%E3%81%A8%E3%81%8D%E3%81%AE%E6%8C%99%E5%8B%95%E3%81%8C%E3%81%8A%E3%81%8B%E3%81%97%E3%81%84%E5%95%8F%E9%A1%8C)
- Add missing call of refresh_burden_state().
- When you present gift to your ally, you can give other items
continuously.
- When you present gift to other NPCs, the game turn passes.
=> Fix strange behavior when you present gift

src/elona/text.cpp
[vanilla bug]
In vanilla these buildings are built on startup (unimplemented feature),
but the data, variable `bddata`, is not saved. Thus, they will vanish
after you save and load the save once. However, the building information
still remain in map data, variable `cell_data`. As a result, when you
stand at the ruins, you see wield system message, "You see \<i18n error\>" or "\<i18n error\>がある".
In vanilla, the message was "You see." or "がある".
- Mine
- Crop
- Art Atelier
- Smuggler's Hideout
- Light House
=> Fix i18n error: undefined building

src/elona/init.cpp
#1287
Due to the above change, the age of your newly created PC became wield. In Elona, character's age is stored as birth year, and calculated in this formula: `age = this_year - birth_year`
=> Fix PC's birth year

runtime/mod/core/config_def.hcl, runtime/mod/core/locale/en/config.hcl, runtime/mod/core/locale/jp/config.hcl, runtime/profile/default/config.hcl, src/elona/config/config.cpp, src/elona/config/config.hpp, src/elona/keybind/input_context.cpp
Add new options: `initial_key_repeat_wait` and `key_repeat_wait`. They allow you to change key repeat wait. Also change the default value of `initial_key_repeat_wait` from 20 to 5 because I feel the previous value is too long. It should improve UX.
```hcl
initial_key_repeat_wait = 5
key_repeat_wait = 1
```
=> Add new options: initial_key_repeat_wait / key_repeat_wait

src/elona/blending.cpp, src/elona/character_making.cpp, src/elona/command.cpp, src/elona/ctrl_inventory.cpp, src/elona/draw.cpp, src/elona/draw.hpp, src/elona/elonacore.cpp, src/elona/equipment.cpp, src/elona/init.cpp, src/elona/item.cpp, src/elona/item.hpp, src/elona/menu.cpp, src/elona/menu.hpp, src/elona/save.cpp, src/elona/ui/ui_menu_character_sheet.cpp, src/elona/ui/ui_menu_equipment.cpp, src/elona/variables.hpp
- [vanilla] Don't go back when you press ESC in change appearance>detail submenu. Instead, go back basic change appearance menu.
- Refactor `menu_change_appearance()`, `menu_change_appearance_equipment()`, `createpcpic()`.
- Improve change appearance menu: show 4 direction at once. It is highly inspired by oor.
- Fix that you cannot close change appearance equipment menu by Enter key due to typo in source code.
- Improve performance of change appearance menu. Load PCC graphics only if you change something.
=> Fix and improve change appearance menu

src/elona/ui/ui_menu_feats.cpp
This PR is a fix for #1227
keybind_manager.cpp sets the global variables key_mode (default key: 'z') and key_identify (default key: 'x'). Therefore I replaced the hard-coded strings with them.
=> Show [F]eat menu keyhint based on keybinding settings

src/elona/main_menu.cpp, src/elona/ui/menu_cursor_history.hpp
`MenuCursorHistory` is similar to `ConfigMenuHistory`, but more general solution for any list menu window to save the current cursor position and restore it in the next time.
=> Add MenuCursorHistory to restore the previous cursor position

src/elona/config/create_config_screen.cpp, src/elona/config/create_config_screen.hpp
Close #1260 
- ~~Remove "Mod Settings" submenu.~~
- ~~Instead, expand each menu to top level.~~
- Sort mods by name (ascending).
- Expand mod config if the mod has only one section.
- If the mod has only one section, the number of Enter keys you need to type decrease by 1.
```hcl
config {
game {
type = "section"
options = {
aaa = true
}
}
}
```
=> Simplify config menu hierarchy

runtime/mod/core/data/dialog/unique/lomias.lua
https://github.com/ElonaFoobar/ElonaFoobar/issues/1342
Check if larnneire is dead instead of checking if larnneire exists.
=> Fix lomias' easter egg event in the initial cave

runtime/mod/template_blank/mod.hcl, src/elona/lua_env/mod_manager.cpp
#1284 
https://github.com/ElonaFoobar/ElonaFoobar/issues/1284#issuecomment-500245800
https://github.com/ElonaFoobar/ElonaFoobar/issues/1284#issuecomment-500248510
- Change `author`, `license`, and `description` field in `template_blank` mod.
- Make validation against mod name strict. Now, upper case is invalid.
=> Fix mod template

src/elona/main_menu.cpp
Close #1367.
If the user presses any 'Select_X' button above 6, code throws an exception. We can just ignore those invalid actions to avoid crashing Elona.
=> Fix main menu crash when an unavailable option was selected via keyboard

src/elona/command.cpp
Close #1366.
Check if moyer is alive.
=> Check if moyer is alive before writing his dialog

src/elona/character.cpp, src/elona/character.hpp, src/elona/command.cpp, src/elona/elonacore.cpp, src/elona/initialize_map.cpp, src/elona/proc_event.cpp, src/elona/talk.cpp, src/elona/talk_npc.cpp
#45
I replaced the numeric legacy ids with the new string based IDs. chara_find can find all characters with the new string id and it therefore calling ensure on the character db will not throw an exception.
=> Add string id based chara_find and replace hardcoded legacy ids

src/elona/command.cpp, src/elona/elonacore.cpp, src/elona/i18n.hpp, src/elona/macro.hpp
Close #1375
- Add non-standard attribute compatible with `[[nodiscard]]` in C++17 each compiler provides to i18n-related functions.
- Fix some text not being shown to players.
=> Add [[nodiscard]] attribute to i18n functions

src/spider/http/backends/boost_asio/request.cpp
Close #1381 
Instead, use `boost::asio::ssl::error::stream_errors::stream_truncated`.
=> Fix build error: SSL_R_SHORT_READ is undefined in OpenSSL 1.1 or later

CMakeLists.txt
When I'm trying to build the latest develop branch I get these errors:
[100%] Linking CXX executable Elona_foobar
/home/vorlent/Projects/ElonaFoobar/src/spider/http/backends/boost_asio/request.cpp:82: error: undefined reference to 'network::uri::has_scheme() const'
/home/vorlent/Projects/ElonaFoobar/src/spider/http/backends/boost_asio/request.cpp:82: error: undefined reference to 'network::uri::scheme() const'
/home/vorlent/Projects/ElonaFoobar/src/spider/http/backends/boost_asio/request.cpp:85: error: undefined reference to 'network::uri::has_host() const'
/home/vorlent/Projects/ElonaFoobar/src/spider/http/backends/boost_asio/request.cpp:87: error: undefined reference to 'network::uri::host() const'
/home/vorlent/Projects/ElonaFoobar/src/spider/http/backends/boost_asio/request.cpp:95: …
=> Add uri to target_link_libraries

src/elona/lua_env/console.cpp, src/elona/net.cpp, src/elona/ui/ui_menu_voting_box.cpp, src/spider/http/backends/boost_asio/request.cpp
- Refactor: delete unused `struct`s.
- Add console command for testing: `httpget`.
- Usage: `httpget URL`
- Fix background image of voting box menu.
- Fix chat list of chat history menu.
- Not all chats were listed before.
- Refactor: fix ambiguous fall-through.
- Fix SSL shutdown error.
- FIXME: it is just a work around, not a correct solution. We just ignore error regardless of whether it is false-positive or not.
=> Fix SSL error

src/elona/lua_env/data_manager.cpp, src/tests/data/registry/load_order/data-update.lua, src/tests/data/registry/load_order/data.lua, src/tests/data/registry/load_order/init.lua, src/tests/data/registry/load_order/mod.hcl, src/tests/lua_data.cpp
Support data editing. `data-update.lua` is always loaded after `data.lua` is loaded. You can modify existing data, add new ones, and remove them in the file.
=> Support data-update.lua

runtime/data/script/kernel/serial.lua, src/tests/lua_serialization.cpp
Close #1397 
Skip fields prefixed by `_` in `Store` object. If `Store` is not a table, the value is directly saved.
This rule is only applied to top level fields, i.e., this process is NOT performed recursively, because we have to save `Handle` object which has `__handle`, `__kind` and `__index`.
=>  Don't save volatile data in Store object

.travis/before_install.sh, CMakeLists.txt, runtime/mod/core/locale/jp/config.hcl, src/util/filepathutil.cpp, src/util/unicode.hpp, src/util/unicode_utf16.hpp
Most of code is borrowed from #1294.
Remove Boost.Locale from dependencies, and instead use utilities borrowed from sol2.
=> Remove Boost.Locale from foobar dependencies

src/elona/gdata.cpp, src/elona/gdata.hpp, src/elona/init.cpp, src/elona/random.cpp, src/elona/random.hpp, src/thirdparty/xoshiro256/splitmix64.hpp, src/thirdparty/xoshiro256/xoshiro256.hpp
- Reset random seed to he global seed + offset. Previously, `randomie()` function  calls `std::random_device`, but the RNG may be slow on some platforms. Also, the function's result is non-deterministic. Now, we use `game_data.random_seed + game_data.random_seed_offset` instead. The offset is incremented every time `randomize()` is called. It improves performance and make RNG deterministic.
- Widen range of global random seed: 2-801 to 1-2000000000.
- Change global RNG from mt19937 to xoshiro256, variant of xorshift. Elona frequently resets the random seed, which slows down the performance of mt19937 engine. Xorshift is much more lightweight algorithm and the performance is not affected by a lot of calls of `randomize()`.
=> Change RNG from mt19937 to xorshift's variant

src/elona/elonacore.cpp
Fix wrong locale key: `core.action.which_direction.cannot_see` -> `core.action.which_direction.cannot_see_location`
=> Fix wrong locale key [ci skip]

.gitmodules, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/org/libsdl/app/SDLActivity.java, android/app/src/main/java/xyz/ki/elonafoobar/ElonafoobarActivity.java, android/app/src/main/java/xyz/ki/elonafoobar/SplashScreen.java, appveyor.yml, runtime/README (en).txt, runtime/README (ja).txt, src/elona/testing.cpp, tools/i18n_checker/src/i18n_checker/main.lua
Rename repository and organization name from ElonaFoobar to elonafoobar. You developers and players do not need to do anything because GitHub ignores repository and organization name's case.
=> Rename repository name to elonafoobar

src/elona/lua_env/mod_manager.cpp, src/elona/profile/profile.cpp, src/tests/filesystem.cpp, src/util/filepathutil.cpp, src/util/filepathutil.hpp
Close #1402.
Check whether a filename is reserved by any system when creating new files or directories.
```cpp
CHECK(is_portable_path("."));
CHECK(is_portable_path(".."));
CHECK(is_portable_path("no-extension"));
CHECK(is_portable_path("README.md"));
CHECK_FALSE(is_portable_path(""));
CHECK_FALSE(is_portable_path("con"));
CHECK_FALSE(is_portable_path("nul.txt"));
CHECK_FALSE(is_portable_path("<>"));
CHECK_FALSE(is_portable_path(";"));
CHECK_FALSE(is_portable_path("foo "));
CHECK_FALSE(is_portable_path("foo."));
CHECK_FALSE(is_portable_path(".vimrc"));
CHECK_FALSE(is_portable_path("abc/xyz"));
CHECK_FALSE(is_portable_path("/usr"));
CHECK_FALSE(is_portable_path("C:\\Program Files"));
```
=> Check reserved path when creating new file or directory

src/elona/data/lua_lazy_cache.hpp, src/elona/data/types/type_ability.hpp, src/elona/data/types/type_asset.hpp, src/elona/data/types/type_buff.hpp, src/elona/data/types/type_chara_chip.hpp, src/elona/data/types/type_character.hpp, src/elona/data/types/type_class.hpp, src/elona/data/types/type_fish.hpp, src/elona/data/types/type_god.hpp, src/elona/data/types/type_item.hpp, src/elona/data/types/type_item_chip.hpp, src/elona/data/types/type_item_material.hpp, src/elona/data/types/type_map.hpp, src/elona/data/types/type_map_chip.hpp, src/elona/data/types/type_music.hpp, src/elona/data/types/type_portrait.hpp, src/elona/data/types/type_race.hpp, src/elona/data/types/type_sound.hpp, src/elona/data/types/type_trait.hpp
Now, `LuaLazyCacheWithLegacyIdTable` which is derived from `LuaLazyCache` has fields and methods related to legacy ID. It can reduce memory usage and detect unintended call of `get_id_from_legacy()` against data type which does not have legacy ID.
=> Refactor: Move legacy ID support out of LuaLazyCache

runtime/data/script/kernel/private/scan_exports.lua, runtime/mod/core/init.lua, src/tests/data/mods/test_export_keys/init.lua, src/tests/lua/exports/eating_effect.lua, src/tests/lua_data.cpp, src/tests/lua_exports.cpp, src/tests/util.cpp
```lua
-- BEFORE:
-- init.lua
local Exports = {}
function Exports.say_hello()
print("hello")
end
-- Returns a table which contains "Exports" field.
return {
Exports = Exports
}
```
```lua
-- AFTER:
-- init.lua
local exports = {}
function exports.say_hello()
print("hello")
end
-- Returns the module table directly.
return exports
```
=> Change how to export modules

src/elona/ctrl_file.cpp, src/elona/lua_env/api_manager.cpp, src/elona/lua_env/api_manager.hpp, src/elona/lua_env/console.cpp, src/elona/lua_env/console.hpp, src/elona/lua_env/data_manager.cpp, src/elona/lua_env/data_manager.hpp, src/elona/lua_env/event_manager.cpp, src/elona/lua_env/event_manager.hpp, src/elona/lua_env/export_manager.cpp, src/elona/lua_env/export_manager.hpp, src/elona/lua_env/handle_manager.cpp, src/elona/lua_env/handle_manager.hpp, src/elona/lua_env/i18n_function_manager.cpp, src/elona/lua_env/i18n_function_manager.hpp, src/elona/lua_env/lua_env.cpp, src/elona/lua_env/lua_submodule.hpp, src/elona/lua_env/mod_manager.cpp, src/elona/lua_env/mod_manager.hpp, src/elona/lua_env/mod_serializer.hpp, src/elona/save_update.cpp
Add `class LuaSubmodule` to organize common code. It has reference to `LuaEnv` and own `sol::environment`. `XyzManager` now inherits `LuaSubmodule` and uses its protected methods.
Also, because `Console` class is rewritten by using `LuaSubmodule`, `CONSOLE` pseudo-mod to capsule side-effects while executing console commands gets unnecessary. Now that the pseudo-mod is removed.
=> Refactor LuaEnv and submodules

runtime/mod/core/data/chara_drop.lua
Fix the bug that Tuwen does not drop anything.
```diff
on_generate = function()
-            if Map.id() == 257 then
+            if Map.id() == "core.pyramid" then
return make_drops({ "core.statue_of_opatos",
"core.platinum_coin",
```
`257` is the ID of Tuwen, not pyramid map's. Also, `Map.id()` returns string ID, not legacy integer ID.
=> Fix that Tuwen does not drop anything

appveyor.yml, deps/install.bat
Fix OpenSSL DLL error on Windows.
- Update submodule windows_deps: add openssl-1.1.1c
- Use windows_deps/openssl-1.1.1c instead of Appveyor-provided OpenSSL.
=> Fix OpenSSL DLL error on Windows

src/elona/ui/ui_menu_charamake_race.cpp
Bug:
1. create a new adventurer.
2. in race menu, set cursor catgod, machinegod, or undeadgod.
3. press right arrow key.
4. crash!
Fix `cs`, the current cursor position, when it points out of range.
=> Fix crash in charamaking race menu

src/elona/chara_db.cpp
Close #1444.
Insert `break` statement to the end of each `case` clause.
=> Fix switch statement's fall-through

src/spider/http/backends/boost_asio/request.cpp, src/spider/http/error.hpp
- Add `default` clause to a non-exhaustive switch statement in `spider` library to suppress compiler warning.
- Raise an error on redirecting (status code: 3xx) to many times. Before, you might receive a 3xx response as a success result on redirecting over `Request::max_redirects()` times. Now, the error handler you pass to `Request::send()` is called to handle too many redirects error.
=> Fix non-exhaustive switch cases / 3xx redirect handling

doc/api/config.luadoc, doc/topics/config.md, src/elona/config/config.hpp, src/elona/lua_env/lua_api/lua_api_config.cpp, src/elona/lua_env/lua_api/lua_api_config.hpp, src/tests/lua/config.lua, src/tests/lua_api.cpp
Since Lua is a dynamically-typed language, there is no rationale to separate functions for each types.
`Config.get_int()`
`Config.get_bool()`
`Config.get_string()`
=> `Config.get()`
`Config.set_int()`
`Config.set_bool()`
`Config.set_string()`
=> `Config.set()`
=> Lua API: unify Config.get_{type} and Config.set_{type}

runtime/locale/en/event.hcl, runtime/locale/jp/event.hcl, src/elona/proc_event.cpp, src/elona/ui.cpp, src/elona/ui.hpp
Close #1450.
- Fix typo in locale key: `core.event.beggars` -> `core.event.blaggers`
- Remove unused deferred event handlers:
- Event 7 is never fired not only in foobar but also in vanilla.
- Event 19 is "welcome showroom" event, but foobar does not support showroom now.
- Split `proc_event()` into each event handler.
- Fix #1450:
- Check whether the player character is in a quest map or not before firing exit event.
=> Fix #1450: duplicated map exit bug

README.md, src/thirdparty/sol2/LICENSE.txt, src/thirdparty/sol2/sol.hpp, src/thirdparty/sol2/sol_forward.hpp
The latest version, sol2 v3.x, has been released, but it requires C++17 features. Since the code of foobar is written in C++14, I updated the version to v2.20.6, compatible with the previous version, which supports C++14.
In this update, there are no bug fixes or breaking changes which affect our code as far as I know.
=> Update 3rd-party library, sol2, from v2.20.2 to v2.20.6

src/elona/adventurer.cpp, src/elona/blending.cpp, src/elona/blending.hpp, src/elona/building.cpp, src/elona/command.cpp, src/elona/ctrl_inventory.cpp, src/elona/elonacore.cpp, src/elona/enchantment.cpp, src/elona/enchantment.hpp, src/elona/equipment.cpp, src/elona/food.cpp, src/elona/food.hpp, src/elona/item.cpp, src/elona/item.hpp, src/elona/item_load_desc.cpp, src/elona/itemgen.cpp, src/elona/magic.cpp, src/elona/menu.cpp, src/elona/menu.hpp, src/elona/turn_sequence.cpp, src/elona/ui/ui_menu_equipment.cpp, src/elona/variables.hpp, src/tests/util.cpp
Avoid direct index access to `inv` (e.g., `inv[ci]`), instead use `Item&` as arguments. This refactoring also reduces usage of global variable `ci`.
=> Refactor: avoid direct index access to inv, instead use Item&

src/elona/init.cpp
Startup fails due to empty default font.
```
0.004 INFO  [system] Elona foobar version 0.5.0 (f81287a5), compiled on Windows-6.1.7601 at 2019-11-20T05:55:52Z
0.131 INFO  [profile] Initialize with 'default'.
0.131 INFO  [profile] Load 'default'.
2.286 INFO  [lua.mod] Found mod core
2.293 INFO  [lua.mod] Loaded mod core
6.147 FATAL [system] Couldn't open C:/ElonaFoobar\font
```
* OS version: Windows 7 SP1 64bit Visual Studio 2019
* Elona foobar verision: f81287a54270ec3eea8727b7f5f13ef24cbc2f24
* Start with a new profile.
* Even if you take over from 0.4.x, a problem occurs.
=> Fixed a bug that the game does not start.

src/elona/ui/ui_menu_mod_info.hpp
Namespace `snail` is under `elona`, not in the top level.
=> Fix wrong forward declaration [ci skip]

src/elona/data/types/type_buff.hpp
`src/elona/types/type_buff.cpp` lacks `#pragma once`.
=> Add missing #pragma once directive [ci skip]

runtime/data/script/kernel/config_dsl.lua
fix up #1443's change
"debug" section is marked as "hidden", but is shown in Options menu.
=> Hide config sections marked as hidden in Options menu

.travis.yml
PRs currently requested are blocked due to this problem about Travis CI failure. We need merge this fix first.
Due to recent Travis' update on macOS environment, `wget` failed to load `libssl`. Added `brew upgrade wget` to fix the problem.
=> Fix Travis CI build on macOS: brew upgrade wget

src/elona/deferred_event.cpp, src/elona/init.cpp
#1455 
- Keep the first event in the event queue while it is being processed.
- Function `event_processing_id()` and other related ones returned unexpected values while some event is being handled.
- Swap the order of two events, ID 2 (Lomias and Larnneire's talk) and 24 (all town initialization). The order was reversed due to #1455's change, which is unintended.
=> Fix up #1455

runtime/data/script/kernel/config.lua, runtime/mod/core/config-schema.lua, src/elona/config.cpp, src/elona/config_menu.hpp
closing #1473
Issue #1473:
- Fix preinit options not loaded (path to JSON value were wrong).
- Fix string options not modifiable via Options menu.
Others:
- Fix default value of `core.game.attack_neutral_npcs`: true -> false
- Fix options whose default value is false not loaded.
- Fix log output's tag: warn -> config
=> Fix various config error

src/elona/quest.cpp
fix #1481
Cause and solution:
`QuestData::immediate()` asserts that `game_data.executing_immediate_quest` must not be zero, but 0 is valid as an index of `quest_data`. Remove the `assert()` macro.
=> Remove unnecessary assertion error which causes crash

README.md
Close #1472.
Add "Note for parallel build" section to mention parallel build.
=> Mention parallel build in README for developers [ci skip]

runtime/data/script/kernel/config.lua, src/elona/config.cpp, src/elona/config_menu.cpp
Fix two crashes:
- Fix crash on opening Option menu.
- Allow mods to have no config options.
=> Fix Elona crash related to config options

doc/api/config.luadoc, doc/api/json5.luadoc, doc/api/rand.luadoc, runtime/mod/core/data/chara_drop.lua, src/elona/activity.cpp, src/elona/adventurer.cpp, src/elona/buff.cpp, src/elona/building.cpp, src/elona/calc.cpp, src/elona/casino.cpp, src/elona/character.cpp, src/elona/command.cpp, src/elona/dmgheal.cpp, src/elona/elonacore.cpp, src/elona/food.cpp, src/elona/item.cpp, src/elona/itemgen.cpp, src/elona/lua_env/lua_api/lua_api_rand.cpp, src/elona/lua_env/lua_api/lua_api_rand.hpp, src/elona/magic.cpp, src/elona/map.cpp, src/elona/mapgen.cpp, src/elona/mef.cpp, src/elona/quest.cpp, src/elona/random.hpp, src/elona/random_event.cpp, src/elona/status_ailment.cpp, src/elona/talk_npc.cpp, src/elona/turn_sequence.cpp
#1480  (see [this comment](https://github.com/elonafoobar/elonafoobar/issues/1480#issuecomment-564053028))
`rnd()` is one of the HSP built-in functions, whose result is capped by `RAND_MAX` in C lang. To emulate it, some of `rnd()` in foobar's codebase are substituted by `rnd_capped()` that has the same upper limit.
`rnd_capped(n)` returns `k` in `[0, m)` where `m` is `min(n, RAND_MAX)`.
The capped version is also added to Lua `Rand` module. The usage is exactly the same as `Rand.rnd()`.
This change will make random number generation in foobar closer to that in vanilla.
=> Limit some of rnd()'s range to emulate vanilla rnd() function.

src/elona/keybind/input_context.cpp
#1229 fixed one bug, but it created another bug.
In vanilla, variable `keybd_wait` is fixed to 100000 while you are pressing <kbd>Shift</kbd>, which causes the bug #1229 resolved. However, the bugfix causes another bug: you cannot run/attack fast even if you are pressing <kbd>Shift</kbd> key.
=> Fix #1229; you cannot run/attack fast

src/elona/magic.cpp
The old source that lacks `#include` compiles, but it depends on compilers and their version.
=> Add missing #include directive

src/elona/quest.cpp
The property might be for checking whether you trade the very item that the client asks, but for now such thing is not checked. To stack quest target items with ease, quest IDs should not be saved.
=> Do not set quest ID to Item::count property of quest target item

src/elona/filesystem.hpp, src/tests/tests.cpp
`boost::filesystem::directory_iterator` has several bugs in Linux:
https://www.boost.org/users/history/version_1_70_0.html
> Fixed possible use of uninitialized data in directory iterator
> increment operation on Linux.
I tried updating Boost to the latest, in which the bug has been fixed,
but CMake does not appear to support latest Boost.
Thus, I rewrite `elona::filesystem::glob_{entries,dirs,files}` functions
without `boost::filesystem::directory_iterator` in Linux.
=> Fix GitHub Actions' Build job on Ubuntu

src/elona/init.cpp
Here is the original message (same as vanilla):
```
Lafrontier presents Elona ver 1.22. Welcome traveler!
```
This variant is neither "Elona ver 1.22" nor developed by "Lafrontier" (the author of the vanilla, a.k.a., Noa).
=> Fix welcome message shown on starting

src/snail/CMakeLists.txt, src/snail/backends/headless/detail.cpp, src/snail/backends/headless/image.cpp, src/snail/backends/sdl/image.cpp
In headless mode (i.e., in testing), libsnail did't raise exceptions
even if calls of SDL functions fail. In CI test, loading image files
occasionally fails for some reason, then the program crashes because of
segfault. Generally speaking, it is very hard to determine the cause of
segfault, especially in remote environment. This commit makes libsnail
raise exceptions in headless mode so that more detailed error log is
reported.
=> Raise exception in libsnail headless mode

doc/api/json5.luadoc, runtime/data/script/kernel/config.lua, src/elona/lua_env/lua_api/lua_api_json5.cpp, src/elona/lua_env/lua_api/lua_api_json5.hpp, src/tests/lua/config.lua
Close #1393
- Use default values.
- Use default values.
- Use default values.
- Just ignore them.
Supported schema:
- `type`: The type of the option value
- `string`
- `integer`
- `float`
- `enum`: The valid values of the option
- `min`: The minimum value of the option value
- Only for integer/float options
- `max`: The maximum value of the option value
- Only for integer/float options
If you set invalid values, foobar uses default values.
`JSON5.parse()`, now, returns a pair of nil and error message on failure instead of raising error.
This change enables the config loading routine, which internally calls the function, to handle not found/invalid format error correctly.
=> Implement config validation

src/elona/lua_env/interface.cpp, src/elona/lua_env/interface.hpp, src/elona/lua_env/lua_env.cpp, src/elona/lua_env/mod_manager.cpp, src/elona/lua_env/mod_version_resolver.cpp, src/elona/lua_env/mod_version_resolver.hpp
Implement `ModIndex::traverse()`, a function which traverses `mod`
folder to construct mod index.
=> Fix that mods except for `core` cannot be enabled in `mods.json`

runtime/locale/en/main_menu.hcl, runtime/locale/jp/main_menu.hcl, src/elona/lua_env/mod_manager.cpp, src/elona/lua_env/mod_manager.hpp, src/elona/lua_env/mod_version_resolver.cpp, src/elona/lua_env/mod_version_resolver.hpp, src/elona/semver.hpp, src/elona/ui/ui_menu_mods.cpp, src/elona/ui/ui_menu_mods.hpp
- List installed mods instead of enabled ones in Mod List menu. They are sorted by their IDs in natural order.
- Make it possible to enable/disable mods via Mod List menu.
=> Enable/disable mods via Mod List menu

.github/workflows/build.yml, CMakeLists.txt
Make `Elona_foobar.app` bundle on macOS to distribute the variant. Before, `*.dylib`s are not included to the distributed binaries, so that library loading error happened in user's environment.
=> Make Elona_foobar.app on macOS

CMakeLists.txt, runtime/data/script/kernel/config.lua, runtime/mod/core/exports/eating_effect.lua, src/elona/data/types/type_item_material.cpp, src/elona/lua_env/api_manager.cpp
Enable `SOL_CHECK_ARGUMENTS` in debug build for detecting potential bugs. Also fixed some potential bugs. They *work* as intended so far, but potentially cause wield things.
=> Enable SOL_CHECK_ARGUMENTS in debug build for detecting potential bugs

src/elona/config.cpp
If you enable network feature on Windows, Elona foobar will freeze. The
whole binary data is surely sent to the remote server, but neither the
success handler nor the failure handler is called. The bug is
reproducible, but the cause hasn't been found yet. Anyway, the network
features are temporarily disabled until the bug resolved.
=> Hotfix/0.6.1: Disable network feature temporarily until the bug is resolved

runtime/mod/core/data/dialog/unique/abyss.lua, runtime/mod/core/data/dialog/unique/doria.lua, runtime/mod/core/data/dialog/unique/lexus.lua, runtime/mod/core/data/dialog/unique/miral.lua, runtime/mod/core/data/dialog/unique/rogue_boss.lua, runtime/mod/core/data/shop_inventory.lua, runtime/mod/core/exports/impl/shop_inventory.lua
With the change of #1521, a floating point number is not treated as
a kind of integer. It is necessary to explicitly use '//', division for
integer.
=> Lua: Fix expressions containing '/', division for float

src/elona/CMakeLists.txt, src/elona/building.cpp, src/elona/building.hpp, src/elona/elonacore.cpp, src/elona/mapeditor/command.cpp, src/elona/mapeditor/command.hpp, src/elona/mapeditor/design_mode.cpp, src/elona/mapeditor/design_mode.hpp, src/elona/mapeditor/undo_history.cpp, src/elona/mapeditor/undo_history.hpp
*It is an experimental feature!*
Support undo (<kbd>z</kbd> key) and redo (<kbd>x</kbd>) in house design mode. The undo history is not shared between housing operations (it's intended). The history has unlimited size so far.
- The shortcut keys cannot be changed.
- Tile filling is not supported.
- No key hint text in log window because it is still experimental.
=> Support undo/redo in house design mode

src/elona/adventurer.cpp, src/elona/ai.cpp, src/elona/autopick.cpp, src/elona/blending.cpp, src/elona/building.cpp, src/elona/calc.cpp, src/elona/character.cpp, src/elona/command.cpp, src/elona/ctrl_inventory.cpp, src/elona/data/types/type_item.cpp, src/elona/data/types/type_item.hpp, src/elona/elonacore.cpp, src/elona/enchantment.cpp, src/elona/enchantment.hpp, src/elona/enums.hpp, src/elona/equipment.cpp, src/elona/food.cpp, src/elona/item.cpp, src/elona/item_db.cpp, src/elona/item_load_desc.cpp, src/elona/itemgen.cpp, src/elona/lua_env/lua_api/lua_api_item.cpp, src/elona/magic.cpp, src/elona/map.cpp, src/elona/menu.cpp, src/elona/talk_npc.cpp, src/elona/turn_sequence.cpp, src/elona/turn_sequence_pc_actions.cpp, src/elona/ui/ui_menu_feats.cpp, src/elona/wish.cpp
#850
Defines enum class ItemCategory instead of hard-coded numbers. ItemCategory is derived from int so this change keeps the compatibility of save data.
=> Define enum class ItemCategory 

Makefile.win, README.md, appveyor.yml, deps/install.bat, src/elona/config.cpp
#1526
Fix crash on Windows caused by OpenSSL's DLL loading error. Elona foobar used pre-built OpenSSL binaries in `deps/windows`, but they might be broken. Now, user-provided OpenSSL is (dynamically) linked. Note that you need to install OpenSSL manually. In Appveyor CI, pre-installed binaries are linked (in `C:\OpenSSL-v111-Win64`).
=> Fix OpenSSL on Windows

runtime/mod/core/locale/jp/lazy/scene.hsp
=> Add missing Japanese double quotation in scene file [ci skip]

runtime/mod/core/data/chara.lua, runtime/mod/core/data/chara_drop.lua
Similar to #1538 
Rich person / noble child / tourist don't drop gems and/or wallets. Also, the number of gems which they may drop is different from that in vanilla.
=> Fix chara drop: rich person/noble child/tourist

src/elona/set_item_info.cpp
For example, a red-colored potion is named "brown potion" when it is unidentified.
The formula to calculate random name is different from that of color.
```cpp
// Random name
name = (item_id % random_seed) % 6;
// Random color
color = (item_id + random_seed) % 6;
// cf. Random name (in vanilla)
name = (item_id + random_seed) % 6;
```
The module operation between item_id and random_seed should be changed to addition like vanilla.
Wrong random name
Correct random name
=> Unidentified item's name is different from its color

doc/api/map.luadoc, src/elona/lua_env/lua_api/lua_api_chara.cpp, src/elona/lua_env/lua_api/lua_api_chara.hpp, src/elona/lua_env/lua_api/lua_api_item.cpp, src/elona/lua_env/lua_api/lua_api_map.cpp, tools/docgen/src/main.rs
`libclang` fails to parse these functions for some reason. As workaround, define `ELONA_DOCGEN` while `tools/docgen/` is running and enclose such code with `#ifndef ELONA_DOCGEN` and `#endif`.
=> `tools/docgen` fails to generate some functions' documentation

Makefile
`APK` and `APK_RELEASE` are unused.
=> Remove unused variable in Makefile

CMakeLists.txt, tools/config.json
The default config file in `runtime/profile/default` is for end-user, and inconvenient for developers. On debug build, this file is copied to `bin/` folder instead of `runtime/profile/default/config.json`. Now, you don't have to disable Norne every time.
=> Overwrite for-user config with for-developer config on debug build

src/elona/attack.cpp, src/elona/calc.cpp, src/elona/character.cpp, src/elona/character.hpp, src/elona/item.cpp
Encapsulate the bit flag operations against the member variable into `struct CombatStyle`. Since the internal representation is kept, this change does not break the existing save data.
=> Refactor `Character::equipment_type` with `struct CombatStyle`

src/elona/adventurer.cpp, src/elona/attack.cpp, src/elona/blending.cpp, src/elona/building.cpp, src/elona/command.cpp, src/elona/ctrl_inventory.cpp, src/elona/dmgheal.cpp, src/elona/dump_player_info.cpp, src/elona/equipment.cpp, src/elona/food.cpp, src/elona/item.cpp, src/elona/item.hpp, src/elona/lua_env/lua_api/lua_api_debug.cpp, src/elona/lua_env/lua_api/lua_api_item.cpp, src/elona/lua_env/lua_class/lua_class_item.cpp, src/elona/magic.cpp, src/elona/text.cpp, src/elona/ui/ui_menu_equipment.cpp, src/elona/ui/ui_menu_item_desc.cpp, src/tests/serialization.cpp, src/tests/util.cpp
Let's eliminate index access to `inv`!
Old interface:
```cpp
std::string itemname(
int item_index,
int number = 0,
int skip_article = 0)
```
New interface:
```cpp
std::string itemname(
Item& item,
int number = 0,
bool with_article = true)
```
It now takes `struct Item` instead of index of `inv`. Also, the third parameter was changed to `bool`, and its meaning was reversed.
The reason 1st parameter `item` does not have `const` qualifier is that the function calls `item_identify()`, which may change `Item::identify_state`. Ideally, `itemname()` should take `const Item&`, but it is hard for now.
=> No inv[] project: refactor itemname()

src/elona/data/base_database.hpp, src/elona/data/types/type_ability.cpp, src/elona/data/types/type_buff.cpp, src/elona/data/types/type_chara_chip.cpp, src/elona/data/types/type_character.cpp, src/elona/data/types/type_fish.cpp, src/elona/data/types/type_god.cpp, src/elona/data/types/type_item.cpp, src/elona/data/types/type_item_chip.cpp, src/elona/data/types/type_item_material.cpp, src/elona/data/types/type_map.cpp, src/elona/data/types/type_map_chip.cpp, src/elona/data/types/type_music.cpp, src/elona/data/types/type_sound.cpp, src/elona/data/types/type_trait.cpp, src/tests/data/registry/data_no_legacy_id/data.lua, src/tests/data/registry/data_no_legacy_id/mod.json
In vanilla, each data is identified by its integer ID. In foobar, all data have unique string IDs, and the data which exist in vanilla have the corresponding integer IDs as well for integration with vanilla (they will be used for save data conversion in the future). However, data which don't exist in vanilla (i.e., mod-defined data) do not have vanilla IDs. In such case, the field `legacy_id` cannot be set. This PR makes `legacy_id` optional, and set `-1` by default to mod-defined data.
=> Make legacy_id optional (default: -1) for mod-defined data

src/elona/activity.cpp, src/elona/ai.cpp, src/elona/blending.cpp, src/elona/command.cpp, src/elona/command.hpp, src/elona/ctrl_inventory.cpp, src/elona/dmgheal.cpp, src/elona/item.cpp, src/elona/item.hpp, src/elona/itemgen.cpp, src/elona/lua_env/lua_api/lua_api_item.cpp, src/elona/talk_npc.cpp, src/elona/turn_sequence.cpp, src/elona/variables.hpp, src/tests/lua_handles.cpp
`ti` is one of the most frequently used global variables in vanilla's source code. It may be an abbreviation of "target item", and widely used as index of `inv`.
`ti` has been totally removed from foobar's source code. These functions below are refactored:
- `activity_others_end()`
- `talk_quest_delivery/supply()`
- `unlock_box()`
- `do_offer_command()`
- `blending_proc_on_success_events()`
- `on_enter()` in `ctrl_inventory.cpp`
- `item_stack()`
- `character_drops_item()`
- `item_drop()`
- `pick_up_item()`
- `do_throw_command()`
=> No inv[] project: remove variable "ti"

src/elona/ai.cpp, src/elona/attack.cpp, src/elona/attack.hpp, src/elona/calc.cpp, src/elona/calc.hpp, src/elona/command.cpp, src/elona/dump_player_info.cpp, src/elona/item.cpp, src/elona/menu.cpp, src/elona/menu.hpp, src/elona/ui/ui_menu_character_sheet.cpp, src/elona/variables.hpp
Remove two global variables: `cw` and `ammo`. `cw` maybe stands for "current weapon". They are now passed to each function as parameters, not global variables. In addition, they were changed from index of `inv` to reference of `struct Item`.
=> No inv[] project: remove "cw" and "ammo"

src/elona/blending.cpp
Close #1561.
* Fix that you may lose blending materials even on success.
* Refactor blending_spend_materials(): remove variable `rpresult`
=> Fix that you may lose blending materials even on success

src/elona/ctrl_inventory.cpp
=> Adjust text spacing in ally's Wear menu

src/elona/menu.cpp
Close #1587.
It should be shown as decimal, not integer.
=> Fix displayed damage scale in character sheet

src/elona/ui/ui_menu_message_log.cpp
Fix text rendering in the message log menu when config `core.font.quality` is set to `high`.
=> Fix text rendering in message log menu

runtime/mod/core/i18n/functions.lua, runtime/mod/core/locale/en/ui.lua, runtime/mod/core/locale/jp/ui.lua, src/elona/ui.cpp
All digits are zero-filled now.
Before:
After:
=> Improve digital clock on the top left

src/elona/talk.cpp, src/elona/talk_house_visitor.cpp, src/elona/talk_npc.cpp
Remove no-effect statements:
```cpp
tc = tc * 1 + 0;
```
Also, simplify assignment statements:
```diff
-tc = tc * (chara_find("core.larnneire") == 0) +
-    (chara_find("core.larnneire") != 0) * chara_find("core.larnneire");
+if (const auto larnneire_chara_index = chara_find("core.larnneire"))
+{
+    tc = larnneire_chara_index;
+}
```
=> Refactor: remove no-effect statements

runtime/mod/core/locale/en/action.lua, runtime/mod/core/locale/jp/action.lua, src/elona/command.cpp
Add 'Hang' to [i]nteract menu to hang arbitrary NPCs (except for that you cannot hang yourself). Of course, the choice is available only in wizard mode.
=> Add 'Hang' to [i]nteract menu to hang arbitrary NPCs

src/elona/turn_sequence_pc_actions.cpp
Function `target_position()` assumes that `cdata.player().enemy_id` is zero, but `core.auto_target` option breaks the assumption. To fix the bug, set 0 to `cdata.player().enemy_id` before calling `target_position()`.
=> Fix player's targeting algorithm when core.auto_target option is on

src/elona/ctrl_inventory.cpp, src/elona/magic.cpp
Close #1611
- Fix not being able to steal items
- In Pickpocket spact, target == player means that you attempts to steal items on the ground, not in someone's inventory.
- Change steal inventory menu UI
- When you try to steal items on the ground, not in someone's inventory, hide money in inventory menu UI. In vanilla, it was player's money, but it was useless information. When you try to steal items from someone, the character's money is displayed in the menu as before.
=> Fix not being able to steal items / change inventory menu UI a bit

src/elona/turn_sequence.cpp
Close #1613.
Save `Character::ai_item` in a variable before reseting the field.
=> Fix that allies do not eat/read/drink items which you pass to him/her

runtime/mod/core/locale/en/ctrl_inventory.lua, runtime/mod/core/locale/jp/ctrl_inventory.lua, src/elona/ctrl_inventory.cpp
Make it possible to assign shortcut on cargo items. However, you cannot use cargo items in area where you cannot do so in vanilla. Now, you can assign any shortcut on eating traveler's food.
=> Make it possible to assign shortcut on cargo items

runtime/mod/core/locale/en/keybindings.lua, runtime/mod/core/locale/jp/keybindings.lua, src/elona/keybind/keybind_actions.cpp, src/elona/lua_env/console.cpp, src/elona/lua_env/console.hpp, src/elona/turn_sequence_pc_actions.cpp
Remove 'toggle_console' action, which shows or hides the in-game console window. The action was bound to F12 key, but the key now triggers 'open_console' action. Toggle Console feature was less frequently used and confused users (#1625).
=> Remove 'toggle_console' action

runtime/mod/core/locale/en/chara_making.lua, runtime/mod/core/locale/jp/chara_making.lua, src/elona/character_making.cpp
New naming convention: `path/to/elonafoobar/profile/<profile name>/save/save_<N>` where `N` is a sequential number starting with 1
Old save folders will not be renamed. With this change, you can name your player character without worrying the name is already used.
=> Change save directory's naming convention

src/elona/character.cpp, src/elona/initialize_map_types.cpp, src/elona/magic.cpp
Close #1639.
Don't call `quest_check()` within `chara_vanquish()`, and call `quest_check()` in the caller of it if needed.
=> Fix no-kill win in arena or pet arena

src/elona/character.cpp, src/elona/item.cpp, src/elona/item.hpp, src/elona/itemgen.cpp, src/tests/util.cpp
* Remove item handles when calling `Item::remove()`.
* Remove and create item handles when calling `Item::copy()`.
* TODO: These handles should be "relocated" instead of creating new handles.
=> Fix relocation of item handle (#1631)

runtime/mod/core/locale/en/ui.lua, runtime/mod/core/locale/jp/ui.lua, src/elona/CMakeLists.txt, src/elona/ctrl_file.cpp, src/elona/json5util.hpp, src/elona/main.cpp, src/elona/main_menu.cpp, src/elona/save_header.cpp, src/elona/save_header.hpp
A new save header file, `header.json`, is created when you save existing saves or create new one in the new version of Elona foobar. It contains these information:
* The version which it was saved in
* Your name
* Your alias
* Your level
* Your race
* Your class
* The current location
* Whether Wizard mode is on or not
* The in-game time
* The time when you played it most recently
* The play time
The old header file, `header.txt`, is updated as it was to integrate with vanilla or variants. Thus, this change does not break compatibility.
=> Add more information to the save selection menu

runtime/mod/core/locale/en/damage.lua, runtime/mod/core/locale/en/death.lua, runtime/mod/core/locale/jp/damage.lua, runtime/mod/core/locale/jp/death.lua, src/elona/dmgheal.cpp, src/elona/element.cpp
This PR fixes 2 issues related to damage handling (`damage_hp()` function).
* Fix some routines related to player's damage by spells or rods.
* Attacks by spells or rods were not regarded as player's. It caused some issues: e.g., casting attack spell against town citizens was not treated as a hostile action.
* Fix damage messages in English, especially when casting spells. (English mode only)
* 3rd-person singular present 's' was not appended to the spell caused by the player character.
=> Fix damage handling/message which the player deals

runtime/data/script/kernel/handle.lua, runtime/data/script/kernel/serial.lua, runtime/mod/core/locale/en/ctrl_inventory.lua, runtime/mod/core/locale/jp/ctrl_inventory.lua, src/elona/blending.cpp, src/elona/building.cpp, src/elona/calc.cpp, src/elona/cell_draw.cpp, src/elona/command.cpp, src/elona/ctrl_file.cpp, src/elona/ctrl_inventory.cpp, src/elona/deferred_event.cpp, src/elona/initialize_map.cpp, src/elona/item.cpp, src/elona/item.hpp, src/elona/item_ref.cpp, src/elona/lua_env/handle_manager.cpp, src/elona/lua_env/handle_manager.hpp, src/elona/lua_env/lua_api/lua_api_debug.cpp, src/elona/lua_env/lua_class/lua_class_item.cpp, src/elona/lua_env/lua_env.cpp, src/elona/talk_npc.cpp, src/elona/text.cpp, src/tests/item.cpp, src/tests/lua_callbacks.cpp, src/tests/lua_handles.cpp, src/tests/serialization.cpp, src/tests/util.cpp, src/util/range.hpp
This PR refactors inventory-related routines a lot for future ambitious goals: 1) unlimited-size inventory and 2) tracking items from the cradle to the grave.
* Remove `__index` field of object handles. The field was for integration with legacy code and no longer necessary.
* Note that this change does not break compatibility: all old save can be loaded without errors.
* Remove unnecessary variable: `iqiality`
* It should be a typo of `iQuality`. `iQuality` is a `#define` macro in vanilla's source code, which is equivalent to `Item::quality` field in foobar. Judging from the lines where `iqiality` appears, the variable is totally unnecessary and should be removed.
* Add equality operators (`==` and `!=`) to `Item` struct.
* They compare items by the memory address. This change can reduce …
=> Refactor inventory-related routines

.github/CONTRIBUTING.md, doc/api/env.luadoc, src/elona/lua_env/lua_api/lua_api_env.cpp, src/tests/lua_api.cpp, tools/incver.py
Add tool to increment mod API/mod versions (`tools/incver.py`).
```
$ ./tools/incver.py --help
usage: incver.py [-h] [-n] target {major,minor,patch}
Increment Elona foobar version.
positional arguments:
target
{major,minor,patch}
optional arguments:
-h, --help           show this help message and exit
-n, --dry-run
```
`target` is either of `APP` or any mods.
=> Add tool to increment mod API/mod versions

src/elona/wish.cpp
When you wish "card <someone>" or "figure <someone>", unique artifacts the character has were recorded in The Oracle. For example, wishing "card mani" or "figure mani" appended "cat's tail" to The Oracle.
=> Fix issue where The Oracle records unexpected items

src/elona/activity.cpp, src/elona/ai.cpp, src/elona/blending.cpp, src/elona/building.cpp, src/elona/calc.cpp, src/elona/casino.cpp, src/elona/character.cpp, src/elona/command.cpp, src/elona/ctrl_inventory.cpp, src/elona/deferred_event.cpp, src/elona/dmgheal.cpp, src/elona/equipment.cpp, src/elona/food.cpp, src/elona/initialize_map_types.cpp, src/elona/item.cpp, src/elona/item.hpp, src/elona/lua_env/lua_api/lua_api_debug.cpp, src/elona/lua_env/lua_env.cpp, src/elona/magic.cpp, src/elona/map.cpp, src/elona/map_cell.cpp, src/elona/mapgen.cpp, src/elona/save.cpp, src/elona/talk_npc.cpp, src/elona/turn_sequence_pc_actions.cpp
Instead, it is encapsulated to inventory iterators (`Inventory::(const_)iterator`). Invalid items, whose number is 0, are automatically skipped by the iterator. Now that you don't have to check its validity by yourself in inventory iterations.
=> Skip validity check (item number is 0) during iterating over an inventory

src/elona/item.cpp
Replace a `assert` macro with a `throw` statement because the former is removed in release build.
=> Fix compile error in release build

doc/api/Chara.luadoc, doc/api/Item.luadoc, doc/api/JSON5.luadoc, runtime/data/script/kernel/handle.lua, runtime/mod/core/data/buff.lua, runtime/mod/core/data/dialog/unique/icolle.lua, runtime/mod/core/data/dialog/unique/renton.lua, runtime/mod/core/data/dialog/unique/rogue_boss.lua, src/elona/lua_env/api/common.hpp, src/elona/lua_env/api/modules/module_Chara.cpp, src/elona/lua_env/api/modules/module_Item.cpp, src/elona/lua_env/handle_manager.cpp, src/elona/lua_env/handle_manager.hpp, src/tests/lua/chara.lua, src/tests/lua/item.lua, tools/docgen/src/main.rs
Instead, some functions to iterate over objects are added:
* `Chara.all()`
* `Chara.non_allies()`
* `Item.player_inventory()`
* `Item.map_inventory()`
`sol::this_state` is an implicit parameter passed by sol runtime. It should not be included in documentation.
=>  Remove `Item.iter()` and `Chara.iter()`; fix LDoc

runtime/data/script/kernel/handle.lua, src/elona/lua_env/api/classes/class_LuaCharacter.cpp, src/elona/lua_env/api/classes/class_LuaItem.cpp, src/tests/i18n.cpp
- Change the result of `LuaItem:__to_string` and `LuaCharacter:__tostring`.
- Object ID is used instead of index.
- Fix `LuaItem`/`LuaCharacter:__tostring` not working when calling these via handles.
- Function `__tostring` should be registered in class' metatable.
=> Change the result of LuaItem:__tostring/LuaCharacter:__tostring

src/elona/lua_env/api/classes/class_LuaAbility.cpp, src/elona/lua_env/api/classes/class_LuaAbility.hpp, src/elona/lua_env/api/classes/class_LuaCharacter.cpp, src/elona/lua_env/api/classes/lua_ref.hpp, src/elona/lua_env/handle_manager.hpp
Changed internal structure of `LuaRef`, the base class of `LuaAbility`. Now `LuaRef` consists of only `obj_id`. It is enough to uniquely refer to an Elona object.
=> Refactor LuaAbility

runtime/data/script/kernel/handle.lua, src/elona/character.cpp, src/elona/ctrl_file.cpp, src/elona/initialize_map.cpp, src/elona/lua_env/handle_manager.hpp, src/tests/lua_handles.cpp
Now, handle objects are indexed by raw pointer of corresponding C++ object. It is safe to cast a raw pointer to Lua's integer type because the size of a raw pointer is greater than or equal to the size of Lua integer.
=> Change handles_by_index to handles_by_pointer

doc/api/classes/LuaItem.luadoc, src/elona/lua_env/api/classes/class_LuaItem.cpp
Remove `LuaItem.index` field because it is unused.
=> Remove LuaItem.index field
