CONTRIBUTING.md, ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md, README.md
Close #2.
* Add ISSUE_TEMPLATE.md for GitHub.
* Add PULL_REQUEST_TEMPLATE.md for GitHub.
* Write CONTRIBUTING.md for contributers.
=> Add information to contribute

README.md
=> Add How To Build and How To Play

i18n.hpp, init.cpp
Close #20.
-1 ask
0 Japanese
1 English
Compatible with Vanilla.
=> The language reflects the setting, "language" in config.json

LICENSE
=> Fix KI's copyright notice

lang/en/ui.lua, lang/jp/ui.lua, text.cpp
Close #33.
`ui.weight` => `ui.unit_of_weight`
=> Rename conflicting keys

__init__.lua, ability.cpp, buff.cpp, character.cpp, class.cpp, item_db.cpp, race.cpp, trait.cpp
Close #34.
`__storage__` field is the actual data storage. It is accessed via `__index` and `__newindex` metamethod.
=> Change the structure of data

Makefile, snail/Makefile
=> Fix Makefile for incremental build

__init__.lua, buff.cpp, buff.hpp, calc.cpp, cat.hpp, data/buff.lua, i18n.cpp, i18n.hpp, init.cpp, lang/en/buff.lua, lang/jp/buff.lua
Close #9.
Implement buff effect in Lua.
```lua
on_refresh = function(self, cc, power, turn)
-- Note: turn is always one now.
end
```
=> [WIP] Feature/implement buff in lua

elonacore.cpp
Close #57.
Some wished items have invalid quality over special.
=> Fix invalid quality of some items

calc.cpp, calc.hpp
=> Fix too low object level when receiving dungeon rewards

calc.cpp
=> Fix calcobjlv() and calcfixlv()

ctrl_inventory.cpp, elonacore.cpp, variables.hpp
Close #49.
Wrong refactoring at 438450d8e2c31a30bc5b545b46af3d5eb7486e5d.
=> Fix not being able to cancel yes/no prompt

elonacore.cpp
=> Fix wrong string key(body_part -> burden)

enums.hpp
=> Simplify enum class curse_state_t

elonacore.cpp
=> Exchange character's position when pressing Shift key

snail/renderer.cpp
=> Delete unneccessary initialization of font

Makefile
Comment out OS dependant options in Makefile.
Please uncomment again if you build Foobar on Windows.
=> Comment out OS dependant options

position.hpp
=> Fix position_t's comparison

elonacore.cpp
Close #114.
Use range-based for statement instead of primary for statement using integer.
This change prevents from accessing to DB by undefined skill ID.
=> Fix invalid access to Lua table

README.md, config.cpp, elonacore.cpp, lang/en/ui.lua, lang/jp/ui.lua, variables.hpp
Close #120.
Toggle autodig by "key_autodig"(default: H). Display the current mode
above status ailments like "Poisoned".
=> Implement autodig mode

CMakeLists.txt
=> Fix wrong comment in CMakeLists.txt

CMakeLists.txt, elonacore.cpp, init.cpp, version.cpp.in, version.hpp
Close #130.
Start with version `0.1.0`, and next release is version `0.2.0`.
=> Versioning by CMake

README.md, config.cpp, elonacore.cpp, variables.hpp
Close #153.
Foobar does not support Windows message box. `runtime/config.json` in `README.md` has been updated.
=> Delete cfg_msg_box option

elonacore.cpp, init.cpp, set_option.cpp
* Delete recursion.
* Create class to unite config menu.
=> Refactor set_option()

README.md, config.cpp, draw.cpp, elona.hpp, set_option.cpp, std.cpp, variables.hpp
Close #158.
Add new option "leashIcon".
0: Don't show
1: Show
=> Show leash icon next to HP bar

CMakeLists.txt, ctrl_file.cpp, elonacore.cpp, foobar_save.cpp, foobar_save.hpp, putit.hpp, variables.hpp
Close #169.
Add new save data, `foobar_save.s1`. It is loaded at the same time `gdata.s1` is loaded.
=> Save autodig mode

cell_draw.cpp, elonacore.cpp, variables.hpp
Close #173.
`cell_itemoncell()` no longer use global variables.
=> Do not use global variables in cell_itemoncell()

elonacore.cpp
=> Fix non-centered Japanese text during scenario scene

elonacore.cpp
=> Delete merge conflict marker

data/character.lua, lang/en/character.lua
Close #190.
Remove dragon putit and spiral putit.
=> Remove test CNPCs

ctrl_inventory.cpp, elonacore.cpp, init.cpp, input.cpp, set_option.cpp, variables.hpp
Close #138.
Render selecting cursor and highlight selected item.
Note that the solution is dirty hack so we must refactor `cs_list()` in the future.
=> Render selecting cursor

config.cpp
=> Save changed options

message.cpp
Close #135.
This is experimental implementation. Because I do not have a key board with number pad, it is not tested at all.
=> Support number pad(experimental)

std.cpp
=> Disable high quality shadow temporarily

draw.cpp, draw.hpp, elonacore.cpp
Close #86.
Experimental implementation.
=> Implement damage popup(experimental)

CMakeLists.txt, autopick.cpp, autopick.hpp, config.cpp, config.hpp, elonacore.cpp, init.cpp, item_material.cpp, item_material.hpp, lang/en/ui.lua, lang/jp/ui.lua, set_option.cpp
Close #35.
Experimental implementation
=> Implement autopick(experimental)

putit.hpp
#208.
The cause is the same as #163.
=> Add missing std:: prefix

character.hpp
=> Add missing include directive(<bitset>)

character.cpp, character.hpp, elonacore.cpp
Close #212.
Expand size of `character::_flags` from 30 to 50.
=> Fix size of bit flags

elonacore.cpp
Close #214.
With this change, Visual C++ build Foobar successfully.
=> Add missing encoding conversion

elonacore.cpp
Close #233.
Check whether the item newly created should be placed on the ground or not.
=> Fix infinite loop at casino

ability.cpp, calc.cpp, cat.cpp, ctrl_file.cpp, elona.hpp, elonacore.cpp, init.cpp, initialize_map.cpp, magic.cpp, main.cpp, proc_event.cpp, putit.hpp, snail/font.cpp, std.cpp, util.hpp
Execute `clang-format` for all C++ source code.
=> clang-format

appveyor.yml
Close #270.
Add `clone_folder` property in `appveyor.yml`.
=> Specify clone_folder in appveyor.yml

config.cpp, config.hpp, elonacore.cpp, set_option.cpp
Close #266.
Restore disabling autosave feature deleted by 3fc6935.
=> Restore disabling autosave feature

menu.cpp
Close #335.
Fix argument passed to `cs_list()`.
=> Fix text color in feat menu

menu.cpp
=> Fix glitch at PC's shop

set_option.cpp, std.cpp
Close #340.
- Extra Race/Class
- Animation Wait/Alert Wait
- Initial Key Wait/Key Wait
=> Add options in game

menu.cpp, ui.cpp
Close #351.
Shows compatible behavior with vanilla.
- Positive trait: blue
- Negative trait: red
- Others: black
=> Fix feat text color

appveyor.yml
- Release build for master branch
- Include CHANGELOG.md, CHANGELOG-jp.md, README.md, README-jp.md, and LICENSE.
- Exclude *.ilk and *.pdb.
=> Improve apppveyor.yml

fov.cpp, fov.hpp, ui.cpp
Close #467.
Extend the size of `fovlist` from 15 to 17.
=> Fix out-of-range access to fovlist

wish.cpp
Close #484.
Return appropriate value.
=> Fix being unable to wish items/skills in wizard mode

command.cpp, enchantment.cpp, enchantment.hpp
=> [WIP] Fix living weapon not gaining enchantments

talk.cpp, talk.hpp
=> Fix talk_guide_quest_client()

card.cpp
Close #156.
Adds the generation count to the deck window.
=> Add generation count to deck

character_making.cpp
=> Fix PCC editor in chara making

character.cpp
Close #472.
If all cells are not accessible and the placed character is the PC, do these things:
- Break wall.
- Kill someone there.
- Open closed doors.
- Remove a certain object which prevents from walking through.
=> Fix infinite loop when entering map

character_making.cpp, input.cpp, input.hpp
=> Check if there is the file whose name is the same as playerid

config.cpp, config.hpp, elona.hpp, elonacore.cpp, input.cpp, set_option.cpp, snail/hsp.hpp, snail/hsp/headless.cpp, snail/hsp/sdl.cpp, snail/input.cpp, snail/input.hpp, std.cpp
Close #525.
- Restore `keyWait` option.
- Respect key wait for enter key/shortcut key(0-9).
=> Polish key sensitivity more

config.cpp, i18n.cpp, init.cpp, lua_env/lua_api.cpp, lua_env/lua_env.cpp, lua_env/lua_env.hpp, main.cpp, snail/application/sdl.cpp, snail/hsp/sdl.cpp
Close #534.
Replace `throw new` with `throw`.
=> Fix errors in SDL to be caught

config.cpp
Close #551.
Define minimum and maximum value and validate each option depending on them.
=> Validate integer options

talk_npc.cpp
Close #576.
Just fix the map ID, which was changed mistakenly...
=> Fix criminal being unable to have business in Derphy

input.cpp
Close #88.
Adds the extra number prompt functions.
=> Implement extra number prompt functions

elonacore.cpp, enums.hpp, input.cpp, snail/hsp/sdl.cpp, talk.cpp
Close #533.
Fine tunes the key delay of backspace/Enter. The behavior of Enter is now closer to that of vanilla.
=> Fine tune the repeat delay of enter/backspace

appveyor.yml
=> Add copy statement for runtime/ folder in Appveyor

shop.cpp
Close #575.
Now items stack, keeping the total amount.
=> Stack goods at shop after generating

character.cpp, character.hpp, mods/core/iter.lua
Close #546.
Fixes `chara_create()` not returning the proper status value if placing the character fails.
=> Report success of chara_create properly based on chara_place

ai.cpp
=> Re-calculate distance between 2 npcs when switching the opponent

src/autopick.cpp
Close #598.
It was decided by voting. Thanks to members in Discord server for voting!
=> Change autopick "to save" mark from "*" to "%"

src/casino.cpp
=> Clear input keys during cards are dealt

src/dmgheal.cpp
=> Use enum property for death_by.other

src/blending.cpp, src/building.cpp, src/casino_card.cpp, src/cell_draw.cpp, src/character_making.cpp, src/character_making.hpp, src/ctrl_inventory.cpp, src/draw.cpp, src/draw.hpp, src/elona.hpp, src/elonacore.cpp, src/init.cpp, src/input.cpp, src/magic.cpp, src/main.hpp, src/main_menu.cpp, src/menu.cpp, src/message.cpp, src/set_option.cpp, src/snail/hsp.hpp, src/snail/hsp/headless.cpp, src/snail/hsp/sdl.cpp, src/std.cpp, src/talk.cpp, src/tcg.cpp, src/ui.cpp, src/variables.hpp
#603 
- Change function parameters.
=> Refactor sprite rendering

runtime/assets.hcl, src/blending.cpp, src/cell_draw.cpp, src/ctrl_inventory.cpp, src/draw.cpp, src/draw.hpp, src/elonacore.cpp, src/init.cpp, src/input.cpp, src/menu.cpp, src/message.cpp, src/talk.cpp, src/testing.cpp, src/ui.cpp
#603 
Implement loading of assets' definition and replace legacy functions.
=> Asset system

src/animation.cpp
Fix up #650.
- Fix wrong arguments passed to `grotate()`.
=> Fix grotate()

runtime/locale/en/chara_making.hcl, runtime/locale/jp/chara_making.hcl, src/character_making.cpp
Moves character making strings to the new translation format.
=> I18N: Externalize character making strings

runtime/locale/en/ui.hcl, runtime/locale/jp/ctrl_inventory.hcl, runtime/locale/jp/ui.hcl, src/menu.cpp, src/ui.cpp
Moves strings in `menu.cpp`/`ui.cpp` to the new translation format.
=> I18N: Externalize menu strings

runtime/locale/en/tcg.hcl, runtime/locale/jp/tcg.hcl, src/tcg.cpp
Moves strings in `tcg.cpp` to the new translation format.
=> I18N: Externalize TCG-related strings

src/bench/lua_callbacks.cpp, src/building.cpp, src/character.cpp, src/character_making.cpp, src/ctrl_file.cpp, src/dmgheal.cpp, src/elonacore.cpp, src/filesystem.cpp, src/filesystem.hpp, src/init.cpp, src/initialize_map.cpp, src/item.cpp, src/itemgen.cpp, src/lua_env/lua_api.cpp, src/lua_env/lua_env.cpp, src/lua_env/lua_env.hpp, src/testing.cpp, src/tests/lua_api.cpp, src/tests/lua_callbacks.cpp, src/tests/lua_handles.cpp, src/tests/lua_serialization.cpp, src/turn_sequence.cpp
Close #651.
Adds the executable directory to the list of directories searched in Lua's `require`.
=> Add executable directory to package.path

runtime/assets.hcl, src/activity.cpp, src/ai.cpp, src/animation.cpp, src/animation.hpp, src/command.cpp, src/dmgheal.cpp, src/draw.cpp, src/draw.hpp, src/elonacore.cpp, src/god.cpp, src/magic.cpp, src/proc_event.cpp, src/talk.cpp
=> Refactor animation

src/draw.cpp, src/initialize_map.cpp, src/std.cpp, src/turn_sequence.cpp
They were added to detect some bug in debugging, and I missed to delete.
=> Delete verbose log to stderr

CMakeLists.txt, runtime/data/lua/private/register_data.lua, runtime/locale/en/config.hcl, runtime/locale/jp/config.hcl, runtime/mods/core/config/config_def.hcl, runtime/mods/core/data/sound.hcl, src/animation.cpp, src/audio.cpp, src/audio.hpp, src/character.hpp, src/db_sound.cpp, src/db_sound.hpp, src/dmgheal.cpp, src/elonacore.cpp, src/filesystem.cpp, src/filesystem.hpp, src/init.cpp, src/lion.hpp, src/magic.cpp, src/optional.hpp, src/snail/audio.hpp, src/snail/audio/headless.cpp, src/snail/audio/sdl.cpp, src/tests/lua_registry.cpp
#604. Close #687.
- Allow sound files to be defined in external `sound.hcl` files.
- Add stereo audio option for some sounds. (enabled by default, to gather feedback)
=> Add positional audio/sound file definition

src/activity.cpp, src/ai.cpp, src/character_status.cpp, src/character_status.hpp, src/command.cpp, src/ctrl_file.cpp, src/ctrl_inventory.cpp, src/elonacore.cpp, src/init.cpp, src/itemgen.cpp, src/magic.cpp, src/proc_random_event.cpp, src/talk.cpp, src/talk_npc.cpp
Close #700. 
Now that the upper limit of your gold and platinum is `2^31-1`.
=> Fix gold/platinum overflow

src/building.cpp
=> Fix wrong enum check when finding building spot

runtime/locale/jp/magic.hcl
=> Adjust JP translation for change material

runtime/locale/en/ctrl_inventory.hcl, runtime/locale/en/food.hcl, runtime/locale/jp/adventurer.hcl, runtime/locale/jp/ctrl_inventory.hcl, runtime/locale/jp/food.hcl, src/elonacore.cpp
#715.
Fixes I18N errors mentioned in #715. (There may be more.)
=> Fix various I18N errors

.travis.yml, CMakeLists.txt, Makefile, Makefile.win, README-jp.md, README.md, android/app/src/main/java/xyz/ki/elonafoobar/ElonaFoobarActivity.java, android/app/src/main/res/values-ja/strings.xml, android/app/src/main/res/values/strings.xml, appveyor.yml, doc/README.md, doc/config.ld, doc/topics/i18n.md, runtime/config.hcl, runtime/locale/en/config.hcl, src/defines.hpp
=> Rename ElonaFoobar to Elona foobar

src/ui.cpp
=> Fix glitch in [w]ear menu

README-jp.md, README.md, runtime/locale/en/config.hcl, runtime/locale/jp/config.hcl, src/character.cpp, src/init.cpp, src/main_menu.cpp, src/version.hpp
=> Rename Foobar -> foobar

runtime/data/talk.txt, runtime/lang/en/buff.lua, runtime/lang/en/ui.lua, runtime/lang/jp/ui.lua, runtime/locale/en/action.hcl, runtime/locale/en/activity.hcl, runtime/locale/en/blending.hcl, runtime/locale/en/config.hcl, runtime/locale/en/crafting.hcl, runtime/locale/en/ctrl_inventory.hcl, runtime/locale/en/damage.hcl, runtime/locale/en/enchantment.hcl, runtime/locale/en/event.hcl, runtime/locale/en/god.hcl, runtime/locale/en/map.hcl, runtime/locale/en/talk_unique.hcl, runtime/locale/en/talk_visitor.hcl, runtime/locale/en/trait.hcl, runtime/locale/en/ui.hcl, runtime/locale/jp/action.hcl, runtime/locale/jp/blending.hcl, runtime/locale/jp/crafting.hcl, runtime/mods/core/locale/en/item.hcl, src/blending.cpp, src/crafting.cpp, src/elonacore.cpp, src/main_menu.cpp, src/menu.cpp
Close #750.
Almost all of changes are typo.
Great thanks to Doorknob, the main translator of omake/oo!
=> Port omake/oo translation

src/building.cpp, src/command.cpp, src/ctrl_file.cpp, src/ctrl_file.hpp, src/elonacore.cpp, src/init.cpp, src/initialize_map.cpp, src/magic.cpp, src/main_menu.cpp, src/map.cpp, src/mapgen.cpp, src/shop.cpp, src/tcg.cpp, src/turn_sequence.cpp
=> Refactor names of ctrl_file operations

runtime/mods/core/data/chara.hcl
=> Fix incorrect character colors

src/talk_npc.cpp
=> Prevent aliasing of "chatval" global by argument "int chatval"

README.md
Updated the link to CONTRIBUTING.md toward .github/CONTRIBUTING.md.
=> Update README.md URL to CONTRIBUTING.md.

src/init.cpp, src/talk.cpp, src/talk.hpp, src/talk_npc.cpp, src/talk_unique.cpp, src/variables.hpp
=> Remove global "chatval"

src/random_event.cpp
Delete debug code about random event in sleep.
=> Delete debug code(random event)

runtime/locale/en/damage.hcl, runtime/locale/jp/damage.hcl, src/elonacore.cpp
#715 
- Fix shooting attack text in Japanese
- Fix throwing attack text in Japanese
=> Fix JP damage text

src/menu.cpp
Close #815.
Calls appropriate functions to handle spells and skills.
=> Fix not being able to pickpocket

runtime/locale/en/ui.hcl, runtime/locale/jp/ui.hcl, src/hcl.hpp, src/i18n.cpp, src/thirdparty/microhcl/hcl.hpp, src/thirdparty/microhil/hil.hpp, src/ui/ui_menu_quest_board.cpp
=> Fix corner case of parsing single '$' in HIL

runtime/locale/en/config.hcl, runtime/locale/jp/config.hcl
=> Add Japanese translation for config option's description

src/ability.cpp, src/activity.cpp, src/casino.cpp, src/elonacore.cpp, src/enchantment.cpp, src/food.cpp, src/initialize_map.cpp, src/magic.cpp, src/mapgen.cpp, src/random.hpp, src/shop.cpp, src/spec.cpp, src/spec.hpp, src/util.hpp
Reduce compiler warnings about implicit type conversions which may lack information.
=> Reduce implicit type conversion warnings

src/activity.cpp, src/audio.cpp, src/building.cpp, src/calc.cpp, src/command.cpp, src/ctrl_file.cpp, src/dmgheal.cpp, src/elonacore.cpp, src/gdata.cpp, src/gdata.hpp, src/god.cpp, src/init.cpp, src/initialize_map.cpp, src/itemgen.cpp, src/lua_env/lua_api/lua_api_chara.cpp, src/magic.cpp, src/mapgen.cpp, src/mef.cpp, src/proc_event.cpp, src/random_event.cpp, src/set_item_info.cpp, src/shop.cpp, src/talk_npc.cpp, src/turn_sequence.cpp, src/ui.cpp, src/ui/ui_menu_character_sheet.cpp
#851.
Adds `GameData`, which will pack to and from `gdata` to maintain save compatibility for the meantime.
=> Add GameData and refactor a few parts of gdata

src/command.cpp
=> Fix living weapon not destroying the last enchantment

src/ui/ui_menu_equipment.cpp
=> Fix glitch of wear menu

src/building.cpp
- Part of key hint does not shown.
- Only the most valuable item is listed.
- Adds a missing key hint.
- Fix heir loom sorting method. Now lists up to 10 items like vanilla.
=> Fix home rank window

src/cell_draw.cpp
=> Fix glitch of small map

src/menu.cpp, src/talk.cpp, src/ui/ui_menu_character_sheet.cpp
=> Fix black pixels(#000) of portraits being transparent

src/message.cpp
```
Before:
[9] You do something.
[10] You do something.
After:
[09] You do something.
[10] You do something.
```
=> Fill minute in message with zeros

src/trait.cpp
=> Fix being able to unacquirable feats

src/activity.cpp, src/command.cpp, src/dmgheal.cpp, src/elonacore.cpp, src/gdata.cpp, src/gdata.hpp, src/init.cpp, src/initialize_map.cpp, src/proc_event.cpp, src/quest.cpp, src/talk_npc.cpp, src/talk_unique.cpp, src/text.cpp
=> Refactor gdata subquest flags

src/calc.cpp, src/ctrl_inventory.cpp, src/elonacore.cpp, src/gdata.cpp, src/gdata.hpp, src/initialize_map.cpp, src/shop.cpp, src/talk_house_visitor.cpp, src/talk_npc.cpp, src/talk_unique.cpp, src/text.cpp
=> Refactor gdata guild fields

src/ctrl_inventory.cpp, src/input.cpp, src/ui/ui_menu_composite.hpp
=>  Go to the previous menu by pressing Ctrl+Tab

runtime/locale/en/action.hcl, runtime/locale/jp/action.hcl, src/turn_sequence.cpp
=> Reload autopick file by pressing Shift+Backspace

src/command.cpp
=> Do not show "Make up who?" prompt if there are no pet around you

src/command.cpp
=> Insert a line break to change ammo message

runtime/locale/en/action_use.hcl, runtime/locale/jp/action_use.hcl, src/command.cpp
Close #918.
If you attempt to extract the pet who has been used a stethoscope, this message will be shown.
> {Name} is your precious ally. You need to unwatch {his or her} health to extract {his or her} gene.
=> Prevent gene machine from destroying your precious ally

src/menu.cpp
Close #911.
PCC Graphics option is...
Full scale:
Shrinked:
=> Fix aspect ratio of full-scale PCC in change apperance menu

src/calc.cpp, src/character.cpp, src/ctrl_file.cpp, src/ctrl_inventory.cpp, src/elonacore.cpp, src/init.cpp, src/initialize_map.cpp, src/mapgen.cpp, src/menu.cpp, src/proc_event.cpp, src/quest.cpp, src/quest.hpp, src/talk.cpp, src/talk_npc.cpp, src/ui/ui_menu_journal.cpp, src/ui/ui_menu_quest_board.cpp
Move `qdata` fields into `QuestData` like for `gdata`/`adata`.
=> Structure qdata into QuestData

runtime/locale/en/chara.hcl, runtime/locale/jp/chara.hcl, src/character.cpp
=> Use raw cdatan instead of character when adding quality parens

CMakeLists.txt, runtime/locale/en/config.hcl, runtime/locale/jp/config.hcl, runtime/mods/core/config/config_def.hcl, src/config/config.cpp, src/lib/fps_counter.cpp, src/lib/fps_counter.hpp, src/lib/profiler.cpp, src/lib/profiler.hpp, src/std.cpp, src/turn_sequence.cpp
It would be used for determining rendering slowdowns.
=> Add Show FPS option

runtime/mods/core/data/item.lua, runtime/mods/core/data/item_chip.lua
=> Change sprite of happy bed/double bed to that of luxury bed

src/audio.cpp
=> Remove full qualification of default music IDs

CREDITS, appveyor.yml, runtime/mods/core/locale/en/lazy/scene.hsp, runtime/mods/core/locale/jp/lazy/scene.hsp, src/elonacore.cpp, src/main_menu.cpp
Close #917.
Port English translation of main scenario's cutscenes from Elonaplus Custom. Great thanks to AnnaBannana, the previous E+C author for allowing us to use your translation in foobar.
=> Port EN translation of cutscenes from E+C

runtime/mods/core/data/item_chip.lua
=> Adjust chain mail's stack height

src/snail/hsp/sdl.cpp, src/snail/input.cpp
=> Fix textbox input behavior

src/character_status.cpp
=> Fix ether disease progress advancing too much

src/elonacore.cpp
=> Check whether the save is compatible with the running Elona

src/audio.cpp
=> Fix wrong sound when you kill someone or pick up something

runtime/locale/en/config.hcl, runtime/locale/jp/config.hcl
=> Add more option descriptions in Japanese

src/elona/elonacore.cpp
Close #1055.
Skip undefined rankn's row.
=> Fix Unknown I18N ID: core.locale.rank._7._N

src/elona/keybind/keybind_actions.cpp
=> Fix diagonal move keys being bound wrong keys

src/elona/ai.cpp, src/elona/building.cpp, src/elona/command.cpp, src/elona/elonacore.cpp, src/elona/god.cpp, src/elona/lua_env/lua_api/lua_api_magic.cpp, src/elona/magic.cpp, src/elona/magic.hpp, src/elona/menu.cpp, src/elona/random_event.cpp, src/elona/talk_house_visitor.cpp, src/elona/talk_npc.cpp, src/elona/turn_sequence.cpp, src/elona/turn_sequence_pc_actions.cpp, src/elona/variables.hpp
Separate large monolithic function, `magic()`, into each effect. It will help to create corresponding Lua functions and externalize them to Lua scripting files. This pull request is the first step of it and does not focus on complete refactoring like #262. #262 was well-designed but too large to test and review.
=> Separate function magic() into each effect

src/elona/ui/ui_menu_character_sheet.cpp
=> Fix number of enchantment stars in character sheet

src/elona/blending.cpp, src/elona/card.cpp, src/elona/casino.cpp, src/elona/ctrl_inventory.cpp, src/elona/menu.cpp, src/elona/talk.cpp, src/elona/ui.cpp, src/elona/ui.hpp, src/elona/ui/ui_menu_config.cpp, src/elona/ui/ui_menu_crafting.cpp, src/elona/ui/ui_menu_ctrl_ally.cpp, src/elona/ui/ui_menu_ctrl_ally.hpp, src/elona/ui/ui_menu_dialog.cpp, src/elona/ui/ui_menu_equipment.cpp, src/elona/ui/ui_menu_feats.cpp, src/elona/ui/ui_menu_game_help.cpp, src/elona/ui/ui_menu_materials.cpp, src/elona/ui/ui_menu_town_politics.cpp, src/snail/filedialog/sdl.cpp
=> Fix text color in list menu

src/elona/animation.cpp
=> Fix glitch of crossbow animation

src/elona/tcg.cpp
=> Fix message text's color in TCG

runtime/data/lua/data.lua, runtime/mods/core/data/chara.lua, runtime/mods/core/data/dialog.lua, src/elona/data/common.hpp, src/elona/data/lua_lazy_cache.hpp, src/elona/data/types/type_chara_chip.cpp, src/elona/data/types/type_item_chip.cpp, src/elona/data/types/type_portrait.cpp, src/elona/dialog/dialog_decoder.cpp, src/elona/dialog/dialog_decoder.hpp, src/elona/draw.cpp, src/elona/draw.hpp
=> Change the separator of fully-qualified IDs from ":" to "#"

src/elona/Android.mk, src/elona/CMakeLists.txt, src/elona/ctrl_inventory.cpp, src/elona/globals.cpp, src/elona/globals.hpp, src/elona/ui/ui_menu_equipment.cpp, src/elona/ui/ui_menu_equipment.hpp
=> Fix visibility of resistances in [w]ear menu not being stored

CMakeLists.txt, src/backtrace.cpp, src/elona/filesystem.cpp, src/main.cpp, src/util/CMakeLists.txt, src/util/backtrace.cpp, src/util/backtrace.hpp, src/util/filepathutil.cpp, src/util/filepathutil.hpp
Adds a backtrace on unexpected exit on Linux.
=> Add backtrace output on Linux

src/elona/audio.cpp, src/elona/ctrl_file.cpp, src/elona/data/types/type_music.cpp, src/elona/data/types/type_sound.cpp, src/elona/i18n.cpp, src/elona/lua_env/mod_manager.cpp, src/elona/lua_env/mod_manifest.cpp, src/elona/spec.cpp
=> Fix mojibake in error message if filepath contains multibyte characters

runtime/profile/_/mod/core/data/dialog/unique/erystia.lua
Fix choices in talk with Erystia which is changed in #1219.
=> Fix choices in talk with Erystia

runtime/data/script/kernel/init.lua, src/elona/lua_env/lua_env.cpp
Adds the `coroutine` library from Lua to the mod API.
=> Add Lua coroutine library

src/elona/input_prompt.cpp
=> Fix key display in yes/no prompt

runtime/profile/_/mod/core/data/buff.lua
Migration of data table performed in #1246 was not perfect for that.
=> Fix type error of buff descriptions

src/elona/casino_card.cpp
=> Fix playing card's characters being colored

src/elona/ui.cpp
The position means "not initialized" "about to be initialized". Because there are some particles at (0, 0) in every frame, they were rendered in every frame before.
=> Don't render weather effect's particle at (0, 0)

src/elona/init.cpp
Close #1223.
Lomias says,
> It was fortunate that we found you before the dark mantle of night
> enveloped this whole valley, almost as if Ehekatl, the goddess of luck
> herself had her eyes upon you.
According to what he said, they found the player character *before night*.
=> Change the time when the story begins: 01:10 -> 16:10

src/elona/ui/ui_menu_equipment.cpp
=> Move additional information in [w]ear menu right by 30 px

runtime/mod/core/data/class.lua
=> Add lock picking skill to developer class

src/elona/building.cpp, src/elona/casino.cpp
- Fix casino_choose_card().
- Delete unused variables.
=> Fix up #1323

src/elona/menu.cpp
=> Add missing space in buff spell description

src/elona/ctrl_file.cpp, src/elona/init.cpp, src/elona/initialize_map_types.cpp, src/elona/variables.hpp
Delete save file `gdatan.s1` and variable `gdatan`.
=> Delete gdatan.s1, no longer necessary

doc/api/enums.luadoc, doc/api/wish.luadoc, src/elona/lua_env/enums/enums.cpp, src/elona/lua_env/enums/enums.hpp, src/elona/lua_env/lua_api/lua_api.cpp, src/elona/lua_env/lua_api/lua_api.hpp, src/elona/lua_env/lua_api/lua_api_wish.cpp, src/elona/lua_env/lua_api/lua_api_wish.hpp, src/elona/wish.cpp, src/elona/wish.hpp, src/util/strutil.hpp, tools/docgen/src/main.rs
- `Wish.wish()`: Wish something you want.
- `Wish.match()`: Check whether `input` matches particular words.
- `Wish.add()`: Add custom wishing.
Also add new notation for Lua code block in LDoc.
```cpp
/*
* > if x then
* >    foo()
* > else
* >    bar()
* > end
*/
```
Comment after `> ` is treated as code block by `docgen`.
=> Add Lua API: Wish module

doc/api/classes/LuaCharacter.luadoc, src/elona/lua_env/lua_class/lua_class_character.cpp
=> Fix ldoc: LuaCharacter.image [ci skip]

Makefile, runtime/mod/core/data/buff.lua, runtime/mod/core/data/dialog/unique/loyter.lua, runtime/mod/core/data/dialog/unique/mia.lua, runtime/mod/core/data/dialog/unique/shena.lua, runtime/mod/core/data/dialog/unique/whom_dwell_in_the_vanity.lua, runtime/mod/core/exports/eating_effect.lua, runtime/mod/core/exports/impl/shop_inventory.lua, runtime/mod/core/i18n/functions.lua, src/tests/lua/chara.lua
- Fix directory name which `luacheck` checks.
- Remove unused `require()` and variables.
=> Fix luacheck

runtime/locale/en/main_menu.hcl, runtime/locale/jp/main_menu.hcl, runtime/mod/template_blank/init.lua, runtime/mod/template_blank/mod.hcl, src/elona/filesystem.cpp, src/elona/init.cpp, src/elona/lua_env/mod_manager.cpp, src/elona/lua_env/mod_manager.hpp, src/elona/main_menu.cpp, src/elona/main_menu.hpp, src/elona/ui/ui_menu_mod_info.cpp, src/elona/ui/ui_menu_mods.cpp
#1222 
#1284 
Template mod is a mod whose name has `template_` prefix. It is not listed as normal mod. Currently, foobar just copies the files in the template mod to the new mod folder.
=> Add Mods menu and Mods>Develop submenu to create a new mod from template

runtime/mod/core/data/item_chip.lua
=> Fix stack_height/offset_y of item chip of simple rack

src/elona/dump_player_info.cpp
Close #1356
* u8 is missing in dump_player_info.cpp
* Pet's gender is the player's gender
=> Fix f11 mojibake

src/elona/character_making.cpp, src/elona/ui/ui_menu_charamake_class.cpp, src/elona/ui/ui_menu_charamake_class.hpp, src/elona/ui/ui_menu_charamake_race.cpp
#1373 
Fix crash on charamaking caused by #1373 refactoring.
=> Fix crash on charamaking

runtime/locale/en/net.hcl, runtime/locale/jp/net.hcl, src/elona/net.cpp
#1380 
- Localize error messages.
- Show human-readable error messages instead of status code like 400.
=> Improve error messages on failure to send/receive messages

src/elona/activity.cpp, src/elona/talk_npc.cpp, src/elona/variables.hpp
The global variable isn't needed at all.
=> Remove global variable sex value

src/elona/draw.cpp, src/elona/elonacore.cpp, src/elona/variables.hpp
The global variable tname was removed
=> Remove global variable tname

runtime/data/script/kernel/private/scan_exports.lua, runtime/mod/core/data/chara.lua, src/elona/dialog.cpp, src/elona/elonacore.cpp, src/elona/lua_env/export_manager.hpp, src/elona/shop.cpp, src/tests/lua_data.cpp, src/tests/lua_exports.cpp
=> Remove exports: prefix

src/elona/elona.hpp, src/elona/std.cpp, src/elona/turn_sequence.cpp, src/elona/turn_sequence_pc_actions.cpp
This code has been implemented in vanilla, but did not work properly. This pul request fixes it.
=> Partial mouse support

.github/CONTRIBUTING.md
Update `.github/CONTRIBUTING.md` to fit the current codebase.
=> Update CONTRIBUTING.md [ci skip]

src/elona/filesystem.cpp, src/tests/filesystem.cpp
=> Expand <LANGUAGE> in path string to current language

runtime/mod/core/locale/en/lazy/book.txt, runtime/mod/core/locale/jp/lazy/book.txt, src/elona/elonacore.cpp
Delete unused text from `mod/core/locale/{en,jp}/lazy/book.txt`.
=> Separate book title information

runtime/data/script/kernel/inspect.lua, src/elona/gdata.cpp, src/elona/gdata.hpp, src/elona/lua_env/lua_class/lua_class_character.cpp, src/elona/lua_env/lua_class/lua_class_character.hpp, src/elona/lua_env/lua_class/lua_class_date_time.cpp, src/elona/lua_env/lua_class/lua_class_item.cpp, src/elona/lua_env/lua_class/lua_class_item.hpp, src/elona/lua_env/lua_class/lua_class_position.cpp, src/tests/lua/tostring.lua, src/tests/lua_api.cpp
Add `__tostring()` metamethod to some of userdata for debugging.
- `LuaCharacter`
- `LuaItem`
- `LuaDateTime`
- `LuaPosition`
=> Add __tostring() metamethod to some of userdata

src/elona/lua_env/mod_manager.cpp, src/elona/lua_env/mod_manager.hpp, src/elona/lua_env/mod_manifest.hpp, src/tests/lua_callbacks.cpp, src/tests/lua_events.cpp, src/tests/lua_exports.cpp, src/tests/lua_handles.cpp, src/tests/lua_mods.cpp, src/tests/lua_serialization.cpp
'mod' is pre-defined mod-local variable. The table is read only and has
'store' field.
=> Change Store object to mod.store

runtime/mod/core/config_def.hcl, src/elona/config/config_menu.hpp, src/elona/config/create_config_screen.cpp, src/elona/spec.cpp, src/elona/spec.hpp
The option which has `step` property is incremented/decremented by the amount of `step`.
=> Add 'step' property to integer config option

doc/api/classes/LuaCharacter.luadoc, src/elona/lua_env/lua_class/lua_class_character.cpp
=> Fix #1445: The documentation of "LuaCharacter::set_flag" is wrong

src/elona/magic.cpp, src/elona/mapgen.cpp
Close #1441.
I found another bug whose cause is the same as #1441, fixing it too.
=> Fix for loop whose end changes at random in each loop

.clang-format, src/elona/activity.cpp, src/elona/ai.cpp, src/elona/blending.cpp, src/elona/casino.cpp, src/elona/character_making.cpp, src/elona/character_status.cpp, src/elona/command.cpp, src/elona/ctrl_inventory.cpp, src/elona/dmgheal.cpp, src/elona/elonacore.cpp, src/elona/enchantment.cpp, src/elona/food.cpp, src/elona/item.cpp, src/elona/lua_env/lua_api/lua_api_internal.cpp, src/elona/lua_env/mod_serializer.hpp, src/elona/magic.cpp, src/elona/quest.cpp, src/elona/talk.cpp, src/elona/talk_house_visitor.cpp, src/elona/talk_npc.cpp, src/elona/turn_sequence.cpp, src/elona/ui/ui_menu_ctrl_ally.cpp
Breaking string literals have often confused me when searching the sources.
=> Change 'BreakStringLiterals' option in .clang-format to 'true'

src/elona/_putit/character.cpp, src/elona/ai.cpp, src/elona/ai.hpp, src/elona/character.hpp, src/elona/elonacore.cpp, src/elona/init.cpp, src/elona/turn_sequence.cpp, src/elona/variables.hpp
- Refactor `ai_check()`.
- Refactor `ai_dir_check_1()`/`ai_dir_check_2()`.
- Delete unused function declarations.
- Refactor `ai_proc_basic()`.
- Refactor `proc_npc_movement_event()`.
- Refactor `ai_proc_misc_map_events()`.
- Rename `Character::_205` / `Character::_206` to `Character::target_position`.
- Since struct `Position` hods 2 integers in the same order as `_205` and `206`, this change does not break save file's compatibility.
=> Refactor character AI routines

src/elona/activity.cpp, src/elona/activity.hpp, src/elona/command.cpp, src/elona/dmgheal.cpp, src/elona/elonacore.cpp, src/elona/item.cpp, src/elona/magic.cpp, src/elona/turn_sequence.cpp, src/elona/turn_sequence_pc_actions.cpp, src/elona/ui/ui_menu_journal.cpp, src/elona/variables.hpp
- Use `Item&` and `Character&` instead of item/character index.
- Separate large functions into small ones.
- Reduce `ci` and `cc`.
=> Refactor src/elona/activity.cpp

.github/workflows/build.yml
Set up GitHub Actions for automated building/testing on Ubuntu and macOS.
=> Setup GitHub Actions experimentally

src/elona/net.cpp
=> Fix unintended switch fallthrough

src/elona/config.cpp, src/elona/elonacore.cpp, src/elona/menu.cpp, src/elona/tcg.cpp, src/elona/tcg.hpp, src/elona/text.cpp, src/elona/variables.hpp
Remove global variables `rtvaln`.
=> Refactor: remove global variables, `rtvaln`

src/elona/activity.cpp, src/elona/building.cpp, src/elona/calc.cpp, src/elona/character.cpp, src/elona/command.cpp, src/elona/ctrl_inventory.cpp, src/elona/elonacore.cpp, src/elona/equipment.cpp, src/elona/get_card_info.cpp, src/elona/god.cpp, src/elona/initialize_map_types.cpp, src/elona/item.cpp, src/elona/itemgen.cpp, src/elona/itemgen.hpp, src/elona/lua_env/lua_api/lua_api_chara.cpp, src/elona/magic.cpp, src/elona/map_special_events.cpp, src/elona/mapgen.cpp, src/elona/mef.cpp, src/elona/quest.cpp, src/elona/talk_npc.cpp, src/elona/tcg.cpp, src/elona/tcg.hpp, src/elona/turn_sequence.cpp, src/elona/wish.cpp
Remove global variable `dbid`.
=> Refactor: remove global variable `dbid`

src/elona/keybind/key_names.cpp, src/elona/keybind/keybind_actions.cpp
Close #1433
Ideally, keybinding should not depend on keyboard layout. It is juts a workaround for v0.6.0 release. Keybinding-related components will be rewritten in the future.
=> Fix '*' key (asterisk) not being able to bind in JIS layout keyboard

runtime/locale/en/main_menu.hcl, runtime/locale/jp/main_menu.hcl, src/elona/main_menu.cpp
=> Show message prompt after creating new mod from template

runtime/data/script/kernel/event_tree.lua
=> Remove debug function EventTree:print(), used nowhere

src/elona/data/init.cpp
Close #1529.
Load all sound data before pre-loading of sound effects.
=> Fix some sound effects not played

runtime/data/script/kernel/config.lua, runtime/mod/core/exports/impl/shop_inventory.lua
With the change of #1521, these codes come to raise type errors. This commit fixes them.
=> Fix type mismatch in Lua scripts

runtime/mod/core/data/chara.lua
Close #1538.
Add the `drops` parameter to Vesda.
=> Fix the drops parameter of Vesda

runtime/locale/en/map.lua, runtime/locale/jp/map.lua
=> Fix i18n error on map name

doc/api/animation.luadoc, doc/api/console.luadoc, doc/api/enums.luadoc, src/elona/lua_env/lua_api/lua_api_animation.cpp, src/elona/lua_env/lua_api/lua_api_console.cpp
Add missing LDoc documentation about `Animation` module.
=> Add missing LDoc documentation about Animation

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Fix trivial typo in GitHub issue templates.
=> Fix GitHub issue templates [ci skip]

src/elona/magic.cpp
Just add comments. e.g.,
```diff
+// Eye of Insanity
bool _magic_636()
{
```
=> Add comments to _magic_# functions in magic.cpp [ci skip]

src/elona/lua_env/console.cpp
Add a new console command for debugging: `wish`
Note: wizard mode only
```
> wish [WISH] [NUMBER]
```
```
> wish
```
Show wish text box.
```
> wish gold
```
Wish "gold".
```
> wish "long sword" 20
```
Wish 20 "long sword"s.
=> Add new console command: wish

src/elona/command.cpp, src/elona/command.hpp, src/elona/variables.hpp
`ri` is a global variable, but not very widely used. `open_box()` and `open_new_year_gift()` were refactored.
=> No inv[] project: remove variable "ri"

src/elona/talk_house_visitor.cpp
=> Fix adventurer's favorite skill

runtime/mod/core/locale/en/autopick.lua, runtime/mod/core/locale/jp/autopick.lua
=> Fix that you can't autopick foods

src/elona/command.cpp
=> Fix text error on searching summoning crystal in show house

src/elona/building.cpp, src/elona/character.cpp, src/elona/character.hpp, src/elona/command.cpp, src/elona/deferred_event.cpp, src/elona/initialize_map_types.cpp, src/elona/lua_env/lua_api/lua_api_chara.cpp, src/elona/map.cpp, src/elona/map_special_events.cpp, src/elona/mapgen.cpp, src/elona/talk_npc.cpp
merge #1591 and `git rebase` before merging  this PR
Make `chara_create()` return a reference of the created character. `initializer_map_types.cpp` and `map.cpp` were refactored by using the return value.
=> Refactor function chara_create()

src/elona/building.cpp
=> Fix flickering in house design mode

src/elona/dmgheal.cpp, src/elona/element.cpp, src/elona/element.hpp
In English, third-person singular present `s` was appended for "you" (second-person), and not so for npc (third-person).
=> Fix damage_hp() message: unexpected parameters were passed to i18n function

src/elona/cell_draw.cpp
In vanilla, rendering character chip (non-walking sprite) consists of 2 phases: 1) copying the chip to a temporary texture with a character-specific tint (e.g., red for red putit's sprite), and 2) copying the temporary texture to the screen or any other current rendering target.
Now, the 2 phases are merged: directly copying the chip with the tint to the screen or the rendering target. The optimization reduces draw calls in every screen update. (Because rendering character chips were fast enough, you might not notice the improvement in the game, though.)
=> Performance improvement: reduce texture copying in draw_npc_chara_chip()

src/elona/status_ailment.cpp
=> Fix golem's getting dimmed

src/elona/enchantment.cpp
Close #1626.
Improve enchantment generate  in enchantment.cpp using WeightedRandomSampler in random.hpp.
=> Improve enchantment generate using WeightedRandomSampler

src/elona/cell_draw.cpp, src/elona/command.cpp, src/elona/ctrl_inventory.cpp, src/elona/map_cell.cpp, src/elona/map_cell.hpp, src/elona/text.cpp, src/elona/turn_sequence.cpp, src/elona/turn_sequence_pc_actions.cpp, src/elona/variables.hpp
Replace `Item::index` with `ItemRef` or `Item&`.
=> Reduce use of Item::index

src/elona/activity.cpp, src/elona/ai.cpp, src/elona/animation.cpp, src/elona/attack.cpp, src/elona/command.cpp, src/elona/fov.cpp, src/elona/fov.hpp, src/elona/lua_env/lua_api/lua_api_fov.cpp, src/elona/magic.cpp, src/elona/text.cpp, src/elona/turn_sequence.cpp, src/elona/ui.cpp
Change its signature and add lot of comments.
=> Refactor fov_los()

runtime/mod/core/data/chara_drop.lua
Because Lua's for loop is "inclusive", the below code A has to be written in Lua like code B.
```cpp
// Code A
for (int i = 0; i < N; ++i)
;
```
```lua
-- Code B
for i = 0, N - 1 do    -- or for i = 1, N do
end
```
=> Fix the number of the loot of rogue boss/the leopard warrior/Silvia

src/elona/blending.cpp
This bug was introduced by #1634.
=> Fix a crash when changing pages in the blending menu

src/elona/lua_env/mod_manager.cpp
With this change, only `mod.json` is required for a valid mod.
=> Allow mods to have no `init.lua`
